### ISSUE TITLE
Unify clearable inputs

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#100]
### Describe the bug

Clearable Dropdown is using a background image in order to show a clear Icon.

![image](https://user-images.githubusercontent.com/361632/72085483-6445b680-32d3-11ea-94c9-388c1d1b4b6e.png)

This is problematic since the Search Input and Calendar component are using a button, this makes it impossible currently to have a unique way of clearing an input/dropdown.

### Steps to reproduce

Open a clearable dropdown
Open a Search Input

### Expected behaviour

All clearable fields shows the same clear icon.

### Actual behaviour

Clearable fields do not share the same clearable icon

### Reproducible demo

https://sg-orbit.netlify.com/?path=/docs/components-dropdown-searchable--default-story#clearable

https://sg-orbit.netlify.com/?path=/docs/components-dropdown-searchable--default-story#clearable

**Comment by patricklafrance** [comment]
Potential solution:

Semantic UI React dropdown accept a `searchInput` prop that we could use to provide a custom `<SearchInput />` component having a clear button.

![image](https://user-images.githubusercontent.com/794579/72101465-be09a900-32f2-11ea-95f7-c224c84c9930.png)

https://react.semantic-ui.com/modules/dropdown/

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L1223
