### ISSUE TITLE
🐛 SAFARI: Inputs have a 2px top/bottom margin computed in Safari 

### ISSUE THREAD

**Issue by tjosepo** [gsoft-inc/sg-orbit#1000]
## Describe the bug

On Safari, `<input>` elements have a default margin of 2px which isn't overwritten by Orbit.

This isn't taken into account by Orbit and leads to some elements being slightly miss-aligned with the input.

![Screen Shot 2022-06-30 at 11 43 43 AM](https://user-images.githubusercontent.com/44372776/176719919-88436ad8-de8a-4f97-b451-6ad761711747.png)
![Screen Shot 2022-06-30 at 11 43 16 AM](https://user-images.githubusercontent.com/44372776/176719965-ad61bc62-7f6d-4a5a-b59f-a9115de01fef.png)

## Steps to reproduce

See [DateInput#Presets](https://orbit.sharegate.design/?path=/docs/date-input--default-story#presets) in Safari.

## Expected results

Input and other elements should be aligned, like in Chrome.

<img width="206" alt="Screen Shot 2022-06-30 at 11 47 34 AM" src="https://user-images.githubusercontent.com/44372776/176720752-beeea0ce-0f92-4c1c-be09-a2d44449e8c4.png">

**Comment by fraincs** [comment]
Great catch! Will provide a fix soon.
