### ISSUE TITLE
❗  Add URL to documentation in JSDoc comments

### ISSUE THREAD

**Issue by tjosepo** [gsoft-inc/sg-orbit#1012]
## Problem to solve

When using Orbit, most components require the developer to have the documentation in mind in order to use the components properly.

If the developer doesn't already have the documentation open, working on Orbit components can result in very big context switch, as the developer will have to open their web browser, go to the Orbit storybook website and then find the component they were using.

## Idea

In order to reduce context switching, JSDoc comments containing an URL to the relevant documentation could be added to components.

This is something [MUI already does.](https://github.com/mui/material-ui/blob/e495fe2b788bc1bd00ee76d52d8611d31ea3089d/packages/mui-material/src/Button/Button.d.ts#L111-L123)

Very crude example, but it could look something like this:

![Screen Shot 2022-07-25 at 8 28 33 AM](https://user-images.githubusercontent.com/44372776/180777796-badccd1a-b2c7-4515-9bf3-0fc1f0fc7874.png)

**Comment by patricklafrance** [comment]
That's a great idea! Could you submit a PR for this?
