### ISSUE TITLE
🐛 Button components shouldn't have a pointer cursor on hover

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#1014]
## Describe the bug

Button components shouldn't have a pointer cursor on hover.

A native HTML button doesn't have a pointer cursor on hover. Try it on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

Not alone on this, Tailwind made the change a few days ago: https://github.com/tailwindlabs/tailwindcss/commit/ed3a4f3032b486d8d328089011def785d6572462

**Comment by fraincs** [comment]
Totally on you with this.

**Comment by fraincs** [comment]
Since buttons can be links I am wondering what you would do with buttonsAsLink? I'd tend to add a cursor pointer to indicate we are leaving the current screen.

**Comment by patricklafrance** [comment]
@fraincs is it a native behavior? Instinctively I wouldn’t think so as it doesn’t give any clue to mobile users

Anyway, I believe buttonAsLink would inherit from the Link component style?

**Comment by fraincs** [comment]
@patricklafrance It does not inherit the component style as it has to look like a button but it's a link.

**Comment by patricklafrance** [comment]
Got it, I mixed the variations. Well if it has to look like a button why shoudn’t it use the same cursor strategy as a button?

Besides, as stated in my previous comment, cursor doesn’t show up on mobile so I doubt it’s useful to use the cursor as a navigation indicator.

**Comment by fraincs** [comment]
True, I was refering to the >  I think this trend will continue as more people become aware that `cursor: pointer` is meant for links from Tailwind discussion

**Comment by fraincs** [comment]
In that regard I think a Select should not have a pointer either.

**Comment by fraincs** [comment]
After some discussions with the design team we will follow what other SASS and Apps does and keep it as it is for now, as the user expect a hand cursor on buttons as Microsoft does it this way.
