### ISSUE TITLE
🐛 An invalid Select has inconsistent colors when hovered

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#1016]
## Describe the bug

When hovered, an invalid select lose it's red border and but keeps it's red text color. It seems inconsistent? I would suggest keeping a red border, might use a slight variance to aknowledge the hovering?

![image](https://user-images.githubusercontent.com/794579/182915823-cdd272ce-50c1-40be-8222-d78a4cec0b9b.png)

## Steps to reproduce

https://orbit.sharegate.design/?path=/docs/select--default-story#validation

**Comment by fraincs** [comment]
It follows the same logic as a valid one except the text is lighter, I think the problem lies in the text color that should be darker, this would improve it's accessibility too.

**Comment by patricklafrance** [comment]
What do you mean by "the text is lighter" ?

My concern is that when hovered the border seem to be black instead of red.

**Comment by fraincs** [comment]
When you look at a regular input and it's text color compared to an invalid select in the standard you have dark text and lighter border 

<img width="441" alt="image" src="https://user-images.githubusercontent.com/361632/185266599-92d4197b-44af-4c64-a5ed-7176b4540cd2.png">

then on hover the border gets darker where with an invalid select before the hovering state the text is lighter than the border which does not follows our convention.

**Comment by fraincs** [comment]
> As long as the colors match

By match you mean text and border?

**Comment by patricklafrance** [comment]
Yup
