### ISSUE TITLE
🐛 A disclosure component content have a 14px as Orbit default font-size is 16px

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#1017]
## Describe the bug

A disclosure component content have a 14px as Orbit default font-size is 16px.

I doubt a disclore component content should have a smaller font-size than the base font-size. It's textutal content.

![image](https://user-images.githubusercontent.com/794579/182916577-24ecc8cc-af28-414b-a076-b6ea6ca494e3.png)

## Steps to reproduce

https://orbit.sharegate.design/?path=/docs/disclosure--default-story

**Comment by fraincs** [comment]
A medium Text is 14px.

![image](https://user-images.githubusercontent.com/361632/184968824-50f57418-df99-4e6b-aa38-0e0eea776676.png)

A Modal with text is 14px by default, Tabs too.

I am not saying this is a good idea but fixing this would mean fixing the Text scale as a whole. This has a lot of implications.

**Comment by patricklafrance** [comment]
I see, well the scale seem broken then.

How come a medium text font size is smaller than the default sont size? Medium should be the default.

What’s the logic being it?

**Comment by fraincs** [comment]
What do you mean by default font size? Are you talking about the browser
default font size or Orbit default font size?

**Comment by patricklafrance** [comment]
What’s the difference for an Orbit application as Orbit set the applicafion default font size?

**Comment by fraincs** [comment]
I meant what do you mean by this: 

> How come a medium text font size is smaller than the default sont size

**Comment by patricklafrance** [comment]
I don't think it matter for an Orbit application as the default Orbit font-size is set as the default font-size on the `<body>` element.

**Comment by fraincs** [comment]
Will validate with design.

**Comment by alexasselin008** [comment]
The medium text-size is 14px, but the default browser size is 16px.  Its the same for Igloo. If we rethink design tokens,  we could bring this discussion into the mix.

This is a visual difference only noticeable in the Orbit documentation, not in the applications. 
I will close this issue since we won't do anything for now. I've tried downgrading the documentation font size to 14, but it looks too small and i would need to fix the entire doc for it to be consisten

**Comment by patricklafrance** [comment]
I consider Orbit default size has being `16px` because it's the `font-size` specified in the `normalize.css` file that we add to every application.

![image](https://user-images.githubusercontent.com/794579/217868743-0fec0181-240c-46c7-a6c3-e65720689cd4.png)

**Comment by alexasselin008** [comment]
I guess this will be adressed by this issue: https://github.com/gsoft-inc/sg-orbit/issues/1072

**Comment by alexasselin008** [comment]
16px is the browser's default size, so font-size 16px on body probably doesn't do anything

**Comment by fraincs** [comment]
> 16px is the browser's default size, so font-size 16px on body probably doesn't do anything

Exactly, font-size: 16px only prevents users from changing their browsers font size and have our components react, #1072 will address it. This is not linked to the core issue though, the main issue is that our medium font size is 14 which might be ok as a button with a 16px font size is too much, same goes with checkbox labels, select text, etc. Our paragraphs could benefit from a higher default size though.

**Comment by patricklafrance** [comment]
I know it's the browser size but we have exporting a normalize style sheet since the beginning to set the body `font-size` to 16px way before we added the textual components to Orbit to ensure `1rem` = `16px`.

Textual componens has been added like 1-2 years after.

It hasn't been added to prevent users from overrding the default browser font-size, I don't even think this features existed at the time or at least we weren't aware it existed.

**Comment by fraincs** [comment]
Setting the default font-size to 16 would mean either having very huge texts everywhere 
see sample: 
<img width="228" alt="image" src="https://user-images.githubusercontent.com/361632/217936014-471e1da9-f08f-45cf-a3c4-16ed830464da.png">

or having most components set texts to sm
