### ISSUE TITLE
🐛 The Button loading state does not prevent onClick

### ISSUE THREAD

**Issue by odrouin** [gsoft-inc/sg-orbit#1018]
## Describe the bug

When adding the disabled state on a button it prevents the onClick from being called when clicking it but when adding the loading state, the onClick is called anyway even if both states have pretty much the same style with a big red circle mouse cursor when hovering it.

## Steps to reproduce

1. `<Button disabled onClick={() => alert("test")}>Click</Button>` does nothing when clicking it.
2. `<Button loading onClick={() => alert("test")}>Click</Button>` triggers the alert when clicking it.

## Expected results

The button should not call the onClick when it is in a loading state.

**Comment by alexasselin008** [comment]
I agree that this is a bug, since it is really expected by the user, since we grey out the control AND add the specific "not-allowed" cursor.
![image](https://user-images.githubusercontent.com/38871812/183108722-ce5be21e-11f6-45ae-8793-4dd2ffb7d100.png)

**Comment by patricklafrance** [comment]
Shopify Polaris is using internally a [use-disable-interaction](https://github.com/Shopify/polaris/blob/main/polaris-react/src/utilities/use-disable-interaction.ts) hook to provide this behavior to components.

We could do something similar.
