### ISSUE TITLE
🐛 TextArea's text doesn't have the right color in dark mode

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#1019]
## Describe the bug

When using a TextArea in dark mode, the text is black instead of being primary.
![image](https://user-images.githubusercontent.com/38871812/183451896-b15d89ce-d7b0-4d8d-9b00-8be46e13249e.png)

## Steps to reproduce

1- Open the doc https://orbit.sharegate.design/?path=/docs/textarea--default-story&globals=colorScheme:dark#default
2- Change the color scheme to dark mode
3- type something in the text area
4- notice the text is black

## Expected results

The text should be color primary

**Comment by alexasselin008** [comment]
A visual regression test should be added in order for this to never happen again!

**Comment by fraincs** [comment]
IIRC we are not testing dark mode as it would double the number of Chromatic tests
