### ISSUE TITLE
🐛 TypeScript type error when using `as` attribute

### ISSUE THREAD

**Issue by tjosepo** [gsoft-inc/sg-orbit#1020]
## Describe the bug

Using the property `as` to replace a component with another one does not update the TypeScript type definitions properly of the component.

This is a problem when trying to use React Router's `Link` component with Orbit's `Button` appearance.

The actual behavior is perfect. It's really just the TypeScript definition that is wrong.

It's easy to fix with `// @ts-ignore`, but that's obviously not desireable.

## Steps to reproduce

```tsx
import { Link } from "react-router-dom";
import { Button } from "@sharegate/orbit-ui";

const Example = () => {
  // Property 'to' does not exist on type 'IntrinsicAttributes & Pick<OmitInternalProps<InnerButtonProps, ...
  return <Button as={Link} to="/somewhere">Go somewhere</Button>;
};
```

**Comment by alexasselin008** [comment]
Refer to this documentation in order to fix your issue: 
https://sg-orbit.netlify.app/?path=/docs/as--page

The code you should be writing looks like this: 
```
import { as, Button } from "@sharegate/orbit-ui";
import { Link as ReactRouterLink } from "react-router-dom";

const RouterButton = as(Button, ReactRouterLink);

<RouterButton to="/somewhere">Go somewhere</RouterButton >
```
