### ISSUE TITLE
🚀 Use individual transform properties instead of transform shorthand

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#1022]
## Description

Now that individual transform properties are supported across the board including Chrome (since 104), using the rotate, scale and translate individually would make our CSS more concise in some situations, as well as more explicit. Modifying a value on hover would not require a redeclaration of the whole transform declaration.

**Comment by fraincs** [comment]
Waiting until Chromatic updates their Chrome version (soon) as many tests fails when we use these properties (Accordion is one of them)

**Comment by patricklafrance** [comment]
Did Chromatic support is now available? I think they release a few updates in the last months. Not sure if it was for Chrome thought.

**Comment by fraincs** [comment]
Sadly the last update is from a year ago

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/361632/214460621-cb6fb194-20be-406f-a135-bd9ba3a52472.png">

**Comment by patricklafrance** [comment]
Wow, this is honestly getting unacceptable.

**Comment by fraincs** [comment]
Totally, this issue is not very important but would be nice to have an end to this. Thinking about closing the issue until chromatic updates as my branch will diverge so much!
