### ISSUE TITLE
❗ Add an "onPresetChange" prop on the DateRangeInput Component

### ISSUE THREAD

**Issue by laurentfrenette** [gsoft-inc/sg-orbit#1026]
## Description

There is currently no way to know which date preset has been selected, and it's also impossible to differentiate the user selecting "Last month" as a preset and the user manually selecting 1 month ago as a start date and today as an end date., which would both give the same dates but the 2 actions are fundamentally different.

**Comment by fraincs** [comment]
What would happen if there is no presets? Should we return nothing if a user uses onPresetChange? Or is there a more sensitive approach that would only work when presets are present.

Thoughts @alexasselin008

**Comment by wasim-abuzaher-sg** [comment]
What's the use case for `onPresetChange` that can't be achieved with `onDatesChange`?

**Comment by laurentfrenette** [comment]
@fraincs The easiest way for us would be to directly access the selectedIndex props of the ButtonPresets component if it was exposed.

If we were to add a "onPresetChange" event on the DateRangInput component, it would need to also generate an "onPresetChange" event when the date is changed without using the dropdown, otherwise we would have no way of knowing the preset is not selected anymore. For example, we could return -1 as the selectedIndex when the date is changed with the date input and not from the preset.

@wasim-abuzaher-sg The use case is that we're working on a feature that would allow users to save their current filters on the Manage page, including the date of creation filter. If the user selects "Last month", he would expect his saved filter to always look for the last month from today's date, and not just the 2 saved dates from when he saved his custom filter.

**Comment by wasim-abuzaher-sg** [comment]
Follow up question, would the user select a month range and expect to see that specific month when they come back (e.g. always August 2022)?

**Comment by wasim-abuzaher-sg** [comment]
Can we modify the `onDatesChange` signature to include preset index?
```
onDatesChange?: (event: SyntheticEvent, startDate: Date, endDate: Date, presetIndex: number) => void;
```
Which would default to -1 if no presets, or if the selected range is not a preset?

**Comment by laurentfrenette** [comment]
@wasim-abuzaher-sg This would also be a good solution!

About your question, we feel that if a user wants to save a specific range of date, he will manually enter the dates in the input whereas if he wants to always look for the last month range, he will select the value in the dropdown. It defeats the purpose of the save filter feature if the user saves "Last month" but end up having to always re-click it when he comes back on the app

**Comment by wasim-abuzaher-sg** [comment]
It's also worth mentioning that saving the preset index in the filter isn't future proof, if in few month you decided to include "Last 14 days" preset because clients want it, you will need to update all previously saved filters, or users will start seeing weird results

**Comment by laurentfrenette** [comment]
> It's also worth mentioning that saving the preset index in the filter isn't future proof, if in few month you decided to include "Last 14 days" preset because clients want it, you will need to update all previously saved filters, or users will start seeing weird results

That's actually a very good point, thanks for pointing this out!

**Comment by alexasselin008** [comment]
> There is currently no way to know which date preset has been selected, and it's also impossible to differentiate the user selecting "Last month" as a preset and the user manually selecting 1 month ago as a start date and today as an end date., which would both give the same dates but the 2 actions are fundamentally different.

Could you describe your use case a bit more. When you say the actions are fundamentally different, what do you mean?

The "preset" are basically quick date selection, so there is no real difference between selecting last month and selecting last month directly in the picker.

**Comment by patricklafrance** [comment]
Without additional information, I tend to agree with @alexasselin008.

Should this issue be closed?
