### ISSUE TITLE
💡 Rethink the way Tile component works

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#1039]
## Problem to solve

In some situations Sharegates's UI requires Tiles that act as Select or Radio to To let the user make a choice while giving more context than with a radio group or a checkbox.

![image](https://user-images.githubusercontent.com/361632/195364572-3d60a262-9cc6-4779-859b-764ca09d41e8.png)

## Idea

Tiles could be split in two RadioTile and SelectTile, making UI like above doable without a tour de force. Uses cases and design would need to be laid out before going forward.

**Comment by alexasselin008** [comment]
This component is probably a "One of" since this is only to mimic a well known component in ShareGate Desktop. Not sure that this is going to be used a lot anywhere else

**Comment by patricklafrance** [comment]
Is this component still in play?

**Comment by fraincs** [comment]
Probably not. as per @alexasselin008 comment.

**Comment by patricklafrance** [comment]
From my undertansing, @alexasselin008 is suggesting to not add this component to Orbit.

**Comment by fraincs** [comment]
This is my understanding too.

**Comment by patricklafrance** [comment]
Ah sorry, I commented on so many issues that I forgot which question I asked on which one 😂

Feel free to close all the issues that you think are not relevant anymore.
