### ISSUE TITLE
💡 Add individual transform properties to StyleSystem

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#1041]
## Description

As individual transform properties are now ✅ in all browsers, and are used in Orbit (https://github.com/gsoft-inc/sg-orbit/issues/1022), adding these to the style props is the next logical step. 

## Checklist

- [ ] Jest tests
- [ ] Documentation

**Comment by alexasselin008** [comment]
duplicate of https://github.com/gsoft-inc/sg-orbit/issues/1022
