### ISSUE TITLE
Mini labels should not have a margin-right when not in a tag

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#106]
### Describe the bug

Labels, when in a button, have a margin right of 8px, this is not an intended behaviour and is expected only when in a tag label.

### Steps to reproduce

1. Use a Label with size mini in a button
2. It has a right margin

### Expected behavior

No margin is applied to a label in a button

### Actual behavior

![image](https://user-images.githubusercontent.com/361632/72355579-c0368380-36b5-11ea-9911-f0eab10c4ae4.png)

**Comment by patricklafrance** [comment]
Wondering if a label in a button should always have a LEFT margin of 8px?

**Comment by fraincs** [comment]
A label in a button can be positioned on the right or left

![image](https://user-images.githubusercontent.com/361632/72362420-24127980-36c1-11ea-9425-97882756fed3.png)

Since Semantic buttons does not wrap the text in a button in an element it is complicated to manage. An option would be to accept a text property on our button and wrap it ourself.

**Comment by patricklafrance** [comment]
Do we really want to support both right and left labels? What's our position on this from a design system standpoint?

Do we have any existing use cases?

**Comment by patricklafrance** [comment]
Here's a suggestion:

- A tag in a button have a right margin of 8px (this is what you intent to do here)
- A label in a button have a left margin of 8px
