### ISSUE TITLE
Negative message component has info icon. 

### ISSUE THREAD

**Issue by kcharen** [gsoft-inc/sg-orbit#1062]
We have info icon for the negative variant of the message component in Orbit. 

## Describe the bug

We would like to have distinct icons for each variant of message component. The proposal is to update the icon for negative variant. 

## Steps to reproduce

N/A

## Expected results

![image](https://user-images.githubusercontent.com/116114318/201949525-e1ed42be-a4ce-4cbb-8fa2-c07e4a21476e.png)

**Comment by kcharen** [comment]
Figma link for NegativeWarning Icon
https://www.figma.com/file/20fCf5sGU27MEvyD2QSF5R/Enhancements-%7C-Issues-%7C-Ideas-%F0%9F%A7%A0?node-id=528%3A176157&t=dLNkTKcb4ONBdkir-1

**Comment by fraincs** [comment]
Before proceeding https://github.com/gsoft-inc/sg-orbit/issues/1063 needs to be done, as the negative Message would use this icon.
