### ISSUE TITLE
🐛 Popover's documentation don't have the correct slot documentation

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#1081]
## Describe the bug

According to the documentation, popover support the following slots.
![image](https://user-images.githubusercontent.com/38871812/207698775-6dbec5da-2885-438e-b6d0-595c7cc26c1f.png)

According to the code, popover support the following slots
![image](https://user-images.githubusercontent.com/38871812/207698843-6cdc549c-9361-4bca-89cb-9135a25c3028.png)

## Expected results

correct slots are documented

## Note

Quick look at all the other component to see if other have the same issue.

**Comment by patricklafrance** [comment]
Seems faster to fix it right away than creating an issue 😂
