### ISSUE TITLE
A label with a nested icon should alter is right padding

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#112]
### Describe the bug

When a label have a nested icon, it should alter is right padding to 8px

### Expected behavior

*Theme*

Add a CSS class "icon" to the label.

*Label component*

Add an `icon` prop that will add the CSS class.

-->

(Write a link to your reproducible demo)

**Comment by fraincs** [comment]
What about when icon is at the start of a label?

https://sg-orbit.netlify.com//?path=/docs/components-label-standard--default-story#icon
