### ISSUE TITLE
A label with a nested button should alter is right padding

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#113]
### Describe the bug

When a label have a nested button, it should alter is right padding to 8px

### Expected behavior

*Theme*

Add a CSS class "button" to the label.

*Label component*

Add an `button` prop that will add the CSS class.

-->

(Write a link to your reproducible demo)

**Comment by fraincs** [comment]
I think we should add a `with-button` class to prevent a clash with the semantic button classes.
