### ISSUE TITLE
A button with a nested right positioned icon should alter the button right padding

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#115]
### Describe the bug

Buttons currently do not support right aligned icons.

### Steps to reproduce

1. Add an icon to a button `<Button icon>Sign Out<SignoutIcon24 className="w6 h6 mr1" /></Button>`
2. The button containing the icon has a left padding of 16 and 24 on the right.

### Expected behavior

The button containing the icon has a left padding of 24 and 16 on the right

An option would be to support labeled icons

https://react.semantic-ui.com/elements/button/#types-labeled-icon

### Actual behavior

![image](https://user-images.githubusercontent.com/361632/72446373-71562000-3781-11ea-9953-1a39ec856ed0.png)

**Comment by patricklafrance** [comment]
Should also think about padding-right when the button is `compact`

Labeled icons is not bad but I am not sure this is the intended behavior of the feature?

Another alternative would be to support a `startIcon` and an `endIcon` though our custom Button component,

This is what [Material UI](https://material-ui.com/components/buttons/) and [Atlaskit](https://atlaskit.atlassian.com/packages/core/button) are doing.
And what

**Comment by patricklafrance** [comment]
After adding a few behaviors to the inputs I believe the following would be more consistant:

- State that a button can only have a single icon at a time, which means a left OR a right icon.
- Accept an `icon` property that would accept an SVG component
- The button component will automatically add the `icon` CSS class to the SVG component
- Position the icon to the right by default
- Accept an `iconPosition` that accept a "left" value. When "left" is specified, the CSS class "with-left-icon" will be rendered on the button.

**Comment by patricklafrance** [comment]
The following will be supported

```
<Button type="button" icon={<AddIcon />}}>
            Cutoff
</Button>
```

and

```
<Button type="button" icon={<AddIcon />}} iconPosition="right">
            Cutoff
</Button>
```
