### ISSUE TITLE
🐛 Error in the docs?

### ISSUE THREAD

**Issue by GSRenaudMorinoft** [gsoft-inc/sg-orbit#1202]
## Describe the bug

The color of the --o-ui-text-alias-alert token example is not the right one. It is set to $alert-7 instead of $alert-6.

## Steps to reproduce

Go to https://orbit.sharegate.design/iframe.html?viewMode=docs&id=tokens--page#text-colors and inspect the Moon span for the alias-alert.

## Expected results

The color should be #D93C37, but instead is #A91414.

**Comment by fraincs** [comment]
Indeed, it was an issue. Good catch.

**Comment by alexasselin008** [comment]
Fixed!
