### ISSUE TITLE
🐛 Illustration component as a child of a TileLink component automatically inheriting rounded corners

### ISSUE THREAD

**Issue by richard-karp** [gsoft-inc/sg-orbit#1215]
## Describe the bug

When using a horizontal TileLink with an Illustration component, the Illustration has a border radius on all four corners

## Steps to reproduce

TileLink component with an Illustration as a child.

## Expected results

Only the two corners the two outer corners of the illustration, top and bottom left for horizontal or top left and top right for vertical, should be rounded

![2023-05-15_14-02-29-0000](https://github.com/gsoft-inc/sg-orbit/assets/4752197/d8e9e914-d1b5-4bb0-87da-838e2bc8914d)

**Comment by alexasselin008** [comment]
Reproductible demo in the documentation: 
```
<TileLink orientation="horizontal">
    <Illustration backgroundColor="alias-accent-light">
        <Image src={Planet} width="100px" alt="Planet" />
    </Illustration>
    <Heading>Buy a ticket</Heading>
    <Content>
        Tickets are not refundable and not transferable. A confirmation email will be sent within
        the next few minutes
    </Content>
</TileLink>
```
