### ISSUE TITLE
❗ XL breakpoint seems a little arbitrary. Should we use 1440px instead?

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#1218]
## Description

In our work, we would like to use a 1440px breakpoint, but Orbit exposes 1280px for `lg` and 1536px for `xl`, but it feels like that last one is a little arbitrary. Would we be open to the idea of changing it for `1440px`?

**Comment by alexasselin008** [comment]
Could you describe a bit more the issue it causes you, just so we have a trace of why we are changing it?

**Comment by LaurentDario** [comment]
As discussed in our Orbit Sync:
We will move the `xl` value to `1440px` instead of `1536px` and just drop the current XL value.
New breakpoints should be:
Size | Media query
-- | --
xs | min-width: 640px
sm | min-width: 768px
md | min-width: 1024px
lg | min-width: 1280px
xl | min-width: 1440px

**Comment by alexasselin008** [comment]
Closed in https://github.com/gsoft-inc/sg-orbit/pull/1219
