### ISSUE TITLE
🐛 opacityHover causes a Warning in the console

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#1221]
We discovered while working on the shared navigation, that the use of `opacityHover` generates a warning in the console that seems to depend on Orbit

## Describe the bug

Using `opacityHover` on a Div adds the `o-ui-o-hover` to the div concerned, but the console seems to suggest that it should be `oUiOHover` instead
![image](https://github.com/gsoft-inc/sg-orbit/assets/234418/5da4343b-7c08-4cd2-91cf-47eecbf97de9)

## Steps to reproduce

Add `opacityHover={1}` to an Orbit element supporting Style props and check the console when running the project.

## Expected results

No error or warning should show in the console

**Comment by fraincs** [comment]
Fixed in #1222
