### ISSUE TITLE
Medium input, button and label font-size should be 16px

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#147]
![image](https://user-images.githubusercontent.com/794579/73073953-80765580-3e86-11ea-8b93-faf51563bc8c.png)

**Comment by patricklafrance** [comment]
@fraincs I updated the issue title. After talking to juju we decided to update the font-size of all medium basic components from 18px to 16px.

**Comment by fraincs** [comment]
Perfect, makes sense.

**Comment by fraincs** [comment]
This means we keep large at 18px?

**Comment by patricklafrance** [comment]
Yes
