### ISSUE TITLE
Change Dropdown placeholder behaviour

### ISSUE THREAD

**Issue by Gcaya** [gsoft-inc/sg-orbit#159]
### Describe the bug

When there is no reason of creation selected and you go to pick one, the component's placeholder should be "Choose a group purpose". Instead, the placeholder displays the first element in the list.

### Steps to reproduce

(Write your steps here:)

1. Go on the groups page
2. Open a group in the list
3. Make sure there is no reason of creation selected
4. Click on the EditableLabel to choose a reason of creation

### Expected behavior

The placeholder should display "Choose a group purpose" if none is selected otherwise it should display the reason.

![image](https://user-images.githubusercontent.com/8711024/73371965-7dafa200-4284-11ea-958c-d4c9bfdfac74.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/8711024/73371871-5d7fe300-4284-11ea-8967-9c648fddf092.png)

**Comment by alexasselin008** [comment]
The parameters used for the dropdown are 

```
<Dropdown
        className="small"
        placeholder="Choose a reason of creation"
        open
        selection
        clearable=true
        onChange={handleChange}
        onOpen={handleOpen}
        onClose={handleClose}
        value={value}
        options={options}
        selectOnNavigation={false} 
        selectOnBlur={false}
    />
```

**Comment by patricklafrance** [comment]
It seems to works fine in our [stories](https://sg-storybook.netlify.com/?path=/story/components-dropdown-searchable--default-story) so I believe the problem might be how you use the component?

Can you confirm please?

Might have something to do with how you specify `value`

**Comment by Gcaya** [comment]
Well in the storybook the problem seems to be the same, if nothing is selected it is written ''Select language'' but once you open the dropdown, the placeholder changes to whatever item is focused. 

The expected behaviour is that if no item is selected and you open the dropdown to select one, the placeholder should stay to ''Select language'' until you've actually selected an item.

**Comment by patricklafrance** [comment]
Oh sorry I misunderstood the problem. Yes you're right. This is quite hard to change though since this behavior is hardcoded in SUI component.

Let me validate first with the designers how they feel about this..

**Comment by patricklafrance** [comment]
Did you talk about this with the designers @fraincs ?

**Comment by Gcaya** [comment]
No, only with @alexasselin008 who proposed to open this issue.

**Comment by fraincs** [comment]
@patricklafrance it'll have to be discussed its something we forgot in our last meeting, my feeling is that its a non issue since it's clear that its a preview of what will happen if you hit enter/click

![image](https://user-images.githubusercontent.com/361632/74556118-4818e300-4f2b-11ea-9297-8efa10973c98.png)

**Comment by fraincs** [comment]
This has been resolved with designers. Closing since non issue.
