### ISSUE TITLE
Support TextArea

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#167]
### Is your feature request related to a problem?

We currently only offer theming for basic input. The textarea are not styled.

Semantic UI React offers an "addon" TextArea component. This means that SUI theme doesn't offer any styling for textarea.

I believe we should add a TextArea component to the @orbit-ui/react-inputs project and offer proper styling.

**Comment by fraincs** [comment]
Are we planning on getting specs from designers?

**Comment by patricklafrance** [comment]
If it's not the same as for the text input, of course.
