### ISSUE TITLE
Large input loading is too big

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#178]
### Describe the bug

(Write your answer here.)
![image](https://user-images.githubusercontent.com/794579/74163438-62cc1e80-4bf0-11ea-80eb-6a5c5b7b8c85.png)

**Comment by fraincs** [comment]
Should this follow the Icon size chart? Weren't we about to revisit it with the designers?

**Comment by patricklafrance** [comment]
I don't know, you tell me!

This is not the same code though. Icons are React component to which we add Tachyons dimensions classes. Loadings are pseudo element that are parts of SUI theme.

**Comment by fraincs** [comment]
The loading is 32x32 the same as the magnifier. I'm going to have to see if we change the scale for loadings with the designers.
