### ISSUE TITLE
Dropdown should default to selectOnNavigation/selectOnBlur to false

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#184]
Semantic defaults for these properties are true, this is the opposite of what our designers expect and should be opt in instead of opt out.

A HOC could be made in order to invert the defaults 

selectOnNavigation={false} 
selectOnBlur={false}

**Comment by patricklafrance** [comment]
While on this, also add a `size` prop to the HOC.

**Comment by fraincs** [comment]
I would add https://github.com/gsoft-inc/sg-orbit/issues/199 to the behaviour we need in a Dropdown HOC
