### ISSUE TITLE
Warning: Failed prop type: Invalid prop `size` of value `mini` supplied to `Label`, expected one of ["tiny","small","medium","large","big","huge","massive"].

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#186]
### Describe the bug

In the button component, default value provided to the Label or Tag component is size="mini".

However, since orbit-ui 5.0, the expected values are ["tiny","small","medium","large","big","huge","massive"].

![image](https://user-images.githubusercontent.com/38871812/74451399-8d66e300-4e4d-11ea-88b0-a2f8402266e5.png)

**Comment by patricklafrance** [comment]
Sorry I though it was already fixed but this is only fixed in https://github.com/gsoft-inc/sg-orbit/tree/support-size-with-icons.

Will release soon.
