### ISSUE TITLE
Input left padding is not validated by designers

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#196]
The padding on the left of an input (when loading) is a necessity but never been discussed with designers. The behaviour inherits some Semantic UI defaults.

### Steps to reproduce

1. Visit https://sg-storybook.netlify.com/?path=/story/chromatic-input--sizes
2. Some paddings are not on our scale (e.g. 37px)

**Comment by patricklafrance** [comment]
Also have a look at SearchInput & Dropdown
