### ISSUE TITLE
Line height documentation typo

### ISSUE THREAD

**Issue by Guillaume-Docquier** [gsoft-inc/sg-orbit#200]
### Describe the bug

The line height 6 (lh6) indicates a value of 15 instead of 1.5

### Steps to reproduce

1. Go here https://sg-orbit.netlify.com/?path=/docs/materials-typography--page#line-height
2. Check the value for lh6

### Expected behavior

It should be 1.5

### Actual behavior

It is 15

![image](https://user-images.githubusercontent.com/16602209/74868517-62d0ca80-5324-11ea-90bb-175b3f0982fe.png)

### Reproducible demo

https://sg-orbit.netlify.com/?path=/docs/materials-typography--page#line-height

**Comment by patricklafrance** [comment]
Fixed, thanks for reporting!
