### ISSUE TITLE
Dropdown focus style is different than other inputs

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#207]
### Describe the bug

Dropdown focus style should be consistent with Date picker, search input and input.

Those components change their border colors when focused. The dropdown, lose his borders instead.

**Comment by fraincs** [comment]
This is something to check with designers blindly following other component can lead to some weird looks.

![image](https://user-images.githubusercontent.com/361632/75049152-b3b50000-5497-11ea-917f-fb19edbbf0c9.png)

see this "double border"

**Comment by patricklafrance** [comment]
Looks fine to me but in no designer!

**Comment by patricklafrance** [comment]
BTW, this is how we do it for the date picker and the search input, maybe we could also have margins between the input and results?

![image](https://user-images.githubusercontent.com/794579/75100427-5dc98080-559b-11ea-84d9-d8a4bed89726.png)

![image](https://user-images.githubusercontent.com/794579/75100432-7043ba00-559b-11ea-8345-29e7126f733e.png)
