### ISSUE TITLE
Inline dropdown doesn't have any focus style

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#211]
### Describe the bug

An inline dropdown should have focus style when a user tab to the dropdown with the keyboard. Currently nothing happen and the user doesn't have any clue what the focused item is.

**Comment by fraincs** [comment]
openOnFocus could be the default behaviour for inline dropdowns, this is what semantic does

**Comment by patricklafrance** [comment]
I don't think we want things popping while the user navigate with tabs.

All our other components only open when they are focused and the user press on the space bar.

**Comment by fraincs** [comment]
Currently tabbing then pressing enter does nothing, this is something to think about.

**Comment by patricklafrance** [comment]
@fraincs yes, you should create a separated issue for this.
