### ISSUE TITLE
Dropdown item should support having icons in his content

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#212]
### Describe the bug

SUI dropdown item support having custom content. We could leverage this to allow having icons in dropdown items content:

![image](https://user-images.githubusercontent.com/794579/75059774-a1dd5800-54ab-11ea-9648-0d32851f76fe.png)

Currently, it's working with the following code:

```
        <Dropdown
            selection
            options={[createMale(), createFemale(), { content: <span>With icon <CalendarIcon /></span>, value: "Frank the tank" }]}
            defaultOpen
        />
```

But the styling is off:

![image](https://user-images.githubusercontent.com/794579/75059824-bc173600-54ab-11ea-91aa-f943f26ce486.png)

Live example available in our SB: `?path=/story/chromatic-dropdown-item--icon-in-content`

**Comment by fraincs** [comment]
This can also be done using floated content https://react.semantic-ui.com/modules/dropdown/#content-floated-content
