### ISSUE TITLE
Dropdown action item are not styled

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#214]
### Describe the bug

Dropdown item of type action have been added but they are not styled.

![image](https://user-images.githubusercontent.com/794579/75074997-e0363f80-54ca-11ea-8b92-1c864682639b.png)

Available in our SB at: `?path=/story/components-dropdown-standard--actions`

**Comment by patricklafrance** [comment]
Not sure if it will be usefull but a CSS class `action` have been added on dropdown item that are actions

**Comment by fraincs** [comment]
Useful. Need to discuss design with designers.
