### ISSUE TITLE
Console warning when Inline DatePicker is first opened

### ISSUE THREAD

**Issue by kingbaub3** [gsoft-inc/sg-orbit#22]
### Describe the bug

When you open an inline DatePicker for the first time, `Warning: componentWillReceiveProps has been renamed, and is not recommended for use.` appears in the devtools console

### Steps to reproduce

1- Click on the date picker to open it.

The warning should appear in the console when it's the first time that the datepicker has been opened.

### Reproducible demo

```javascript
const RenderFunction = () => {
    const noop = () => {};

    return <InlineSingleDatePicker onDateChange={noop} />;
};

**Comment by patricklafrance** [comment]
As discussed, we are waiting for a fix from react-dates!
