### ISSUE TITLE
Add grid-layout support to our Tachyons utilities?

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#222]
### Is your feature request related to a problem?

Should we offer grid-layout support with our Tachyons utilities? I think a few products are starting to use this feature?

We could add something similar to: https://github.com/bobek-balinek/tachyons-grid-layout

**Comment by fraincs** [comment]
This might be useful for basic cases of equal widths columns, apart from that the very nature of grid doesn't really fit with atomic classes.

**Comment by patricklafrance** [comment]
I see, I am not familiar enough with css grid-layout to challenge what you are saying. Let's wait then.
