### ISSUE TITLE
Search Input style should follow dropdown logic

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#225]
![image](https://user-images.githubusercontent.com/361632/75696447-9b07cf80-5c79-11ea-93fb-aa79de5bd667.png)

### Describe the bug

Since hitting down arrow on your keyboard selects the first choice, there should not have a gap between the input and the results since this indicates that the choices are part of the input.

### Steps to reproduce

1. Start a search in a Search Input
2. Hit down

### Expected behavior

The results should be attached to the input. 

Note : 
![image](https://user-images.githubusercontent.com/361632/75696712-0487de00-5c7a-11ea-9640-d9f94c4cb55a.png)

The date picker is ok since tabbing moves to the selection zone, tabbing is like jumping while down is like walking.

This has been validated with designers.

**Comment by patricklafrance** [comment]
I am not sure I follow here, the dropdown is the only one that is different (there is an issue for this btw), why would we want to adapt all the other components instead of fixing the dropdown?

**Comment by fraincs** [comment]
> It seems quite common to have spaces between the input and the results, have a look at the following super popular libraries:

When looking at those libraries, I notice that the initiator of the dropdown is not a dropdown but a button, therefore these act more as a menu, versus a select https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

Selecting one of the option does not reflect on the initiator (button). This is a distinction I would make which is why I think the date picker is ok the way it is.

**Comment by patricklafrance** [comment]
Depends on which librairy you are looking at. For example, react-select is also a searchable input.

That being said, depending on which configuration we choose for our dropdown we also have dropdowns that have a button initiator (standard & inline) or an input (searchable).

**Comment by patricklafrance** [comment]
I though about this and this is not about the "initiator", this is about selecting a value (select) versus having a list of non selectable links (menu).

Orbit will build `<Select />` and `<Menu />` component on top of SUI original `<Dropdown />` components. We might provide some kind of abstract dropdown that will contains a few customization but the user should only use Select and Menu components.
