### ISSUE TITLE
Illegal rule in DateRangePicker's stylesheet

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#23]
### Describe the bug

When running ShareGate: Apricot, the following warning is displayed in the console.

```
backend.js:6 StyleSheet: illegal rule: 

.input.jsx-2462695752:not("disabled"){cursor:text;}

See https://stackoverflow.com/q/20007992 for more info 
    in JSXStyle (created by DatePickerTextboxInput)
    in DatePickerTextboxInput (created by DateRangePickerInputInner)
    in DateRangePickerInputInner (created by Anonymous)
    in Anonymous (created by Popup)
    in Popup (created by DatePickerAnchor)
    in DatePickerAnchor (created by DateRangePicker)
    in DateRangePicker (at activity-header.jsx:84)
    in ActivityHeader (at active-activity-page.jsx:38)
    in ActiveActivityPage (at activity-page.jsx:14)
    in ActivityPage (at app-route.jsx:8)
    in Router.Consumer (created by Route)
    in Route (at app-route.jsx:4)
    in AppRoute (at render-route.jsx:21)
    in AuthenticatedRouter (at root-router.jsx:35)
    in Router (at app/​index.jsx:38)
```

### Steps to reproduce

1. Locally run Apricot
2. Go to the Activity Page
3. Open console

### Expected behavior

No warning about illegal rules in stylesheets

### Actual behavior

The warning

### Reproducible demo

The ShareGate Apricot's private repository

**Comment by patricklafrance** [comment]
@alexasselin008 does it also happens in production?

If not, it might be related to the following issue: https://github.com/zeit/styled-jsx/issues/404

The solution like the solution would be configured styled-jsx with `optimizeForSpeed` straight in Orbit.

**Comment by alexasselin008** [comment]
The warning is not present in production, only on our dev environment

**Comment by patricklafrance** [comment]
Ok thanks, let’s try to fix this after the holiday.

**Comment by patricklafrance** [comment]
Will wait for this since we are considering https://github.com/gsoft-inc/sg-orbit/issues/153
