### ISSUE TITLE
A Tag in a Button does not appear or is not a circle

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#234]
### Describe the bug

I've run into a case where the Tag in a button in a button group does not render correctly.
![image](https://user-images.githubusercontent.com/38871812/75778541-fee7d200-5d25-11ea-8c91-00b8131d676b.png)

### Steps to reproduce

The same component rendered in 3 different divs give 3 different results 
![image](https://user-images.githubusercontent.com/38871812/75778966-c72d5a00-5d26-11ea-8000-e8d75126c2dc.png)

![image](https://user-images.githubusercontent.com/38871812/75778991-cf859500-5d26-11ea-886e-e76a0d7e0e5d.png)

![image](https://user-images.githubusercontent.com/38871812/75779139-196e7b00-5d27-11ea-9a6a-f3019bb0c378.png)

### Expected behavior

The Tag is circular and visible in every scenarios

### Reproducible demo

I've reproduced the code in a sandbox (CRA starter + orbit 7.0)
[Orbit-Tag.zip](https://github.com/gsoft-inc/sg-orbit/files/4281410/Orbit-Tag.zip)

**Comment by patricklafrance** [comment]
Will need to talk with the designers. Last time we had a discussion about groups, they only wanted minimal support for groups, which means no embedded tags.
