### ISSUE TITLE
Animate opacity instead of z-index when datepicker popup appears

### ISSUE THREAD

**Issue by kingbaub3** [gsoft-inc/sg-orbit#24]
### Is your proposal related to a problem?

When an item is covered by the datepicker popup and it has a z-index greater than 0, the item is briefly displayed on top of the datepicker popup. 

See: 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/6119223/67527970-42e70e00-f686-11e9-9878-8a7a696c329e.gif)

### Describe the solution you'd like

The popup should be animated based on `opacity`, not `z-index`. That way, it would have a smooth transition without interferring with the layout of the page it's in. 

### Describe alternatives you've considered

A way to overcome this would be to have the ability to set the z-index of the popup when it appears instead of relying on the default (`z-index: 0`, then animated to 10).

To play with z-indexes is hard since we cannot predict whether the popup will be covered by a modal or other components. That is why this solution, paired with the first one, should cover up most use cases. 

### Additional context

There is possible workaround to solve our problem without changing this library. To do so, it requires to play with `position: absolute` to remove the need to set the z-index on the element in the page. This workaround makes the HTML code hard to read and difficult to think about.

**Comment by patricklafrance** [comment]
@fraincs definitely related to what you were trying to fix earlier today!

**Comment by patricklafrance** [comment]
A configurable zIndex props is already available and the animation is already based on opacity. I guess somewhere between the time you opened this PR and now.

To be safe, I added a few chromatic stories to ensure we don't introduce any regression on this.

Feel free to re-open if you still experience issues.
