### ISSUE TITLE
Inline dropdown should support error state

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#242]
### Describe the bug

An inline dropdown doesn't support error state:

```
            <Dropdown
                placeholder="Gender"
                inline
                error
                options={GENDERS}
                className="mr5"
            />
```

![image](https://user-images.githubusercontent.com/794579/75925330-86bd0180-5e36-11ea-8f17-378c1b0f0022.png)

![image](https://user-images.githubusercontent.com/794579/75925589-efa47980-5e36-11ea-8e4f-bc523d6ec7b0.png)

**Comment by fraincs** [comment]
I totally agree. No error state for dropdowns have been agreed upon with designers, this is something to do before going further.

**Comment by patricklafrance** [comment]
Ok, but it has to be done ASAP since the standard select already support error. If we add a functionnality to the select it must work for every variants, otherwise we remove the functionnality.

**Comment by fraincs** [comment]
the standard select supports error but nothing has been validated

**Comment by patricklafrance** [comment]
got it, I don't mind removing it from the docs then until it's validated.

That being said, I believe all our inputs controls should come with support for error state.
