### ISSUE TITLE
Hovered readonly checkbox shouldn't display a hand cursor.

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#249]
### Describe the bug

When a readonly checkbox is hovered, the cursor shouldn't change.

![image](https://user-images.githubusercontent.com/794579/76343986-3848b080-62d7-11ea-98f0-254e6c3e79cb.png)

Repro in Storybook: ?path=/docs/components-checkbox--readonly

Other components have the same problem:

Radio: ?path=/docs/components-radio--readonly
Toggle: ?path=/docs/components-toggle--readonly
Input: ?path=/docs/components-input--readonly

**Comment by fraincs** [comment]
Need to add relevant chromatic tests

**Comment by patricklafrance** [comment]
It's already available: ?path=/story/components-checkbox--readonly
