### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#25]
### Describe the bug

The DatePicker control uses lifecycle method that are being deprecated.

The componentWillUpdate  function should be :
* removed and move the data fetching code or it's side effects to componentDidUpdate.
* or renamed from componentWillUpdate to UNSAFE_componentWillUpdate 

### Steps to reproduce

1. Open Sharegate: Apricot
2. Go to the settings page
3. Open the date picker in the External Sharing Policy
4. Check the console

### Expected behavior

No warnings are displayed in the console.

### Actual behavior

When using the DatePicker in our application, we receive the following warning : 
![image](https://user-images.githubusercontent.com/38871812/67772966-56e99180-fa31-11e9-8b66-853ebc85b6ab.png)

**Comment by patricklafrance** [comment]
After more testing, this is still not fixed.
