### ISSUE TITLE
Button with a label doesn't render well for all sizes.

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#255]
### Describe the bug

![image](https://user-images.githubusercontent.com/794579/76877347-9e8a8180-6849-11ea-9531-4969d09f898b.png)

Repro available in SB at: ?path=/story/chromatic-button-standard--default

**Comment by fraincs** [comment]
Are we expecting the labels to change in size?

**Comment by patricklafrance** [comment]
Seems like a great question for our designer friends

**Comment by fraincs** [comment]
It was decided that these will not change in size as it's secondary information, and it look weird when bigger.
