### ISSUE TITLE
Label button should adapt to label size

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#256]
### Describe the bug

(Write your answer here.)
![image](https://user-images.githubusercontent.com/794579/76878312-07262e00-684b-11ea-8c82-3d092e2f63cb.png)

Repro in SB: ?path=/story/chromatic-label-button--size

**Comment by fraincs** [comment]
The smallest size of button available in Orbit is tiny which is 24px. I don't see a good option if we want a. smaller button in a tiny label.

**Comment by patricklafrance** [comment]
Should we add more sizes for circular buttons? @fraincs

**Comment by fraincs** [comment]
I think so.
