### ISSUE TITLE
SingleDatePicker's Apply button should have a button type="button", not submit

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#27]
### Describe the bug

When using a InlineSingleDatePicker inside a Form, selecting a date will cause my form to be submitted unintentionally.

### Steps to reproduce

1. Open Sharegate Apricot
2. In the settings page, try changing the External sharing's starting date
3. Click apply and observe the logs.

### Expected behavior

A date is selected and the form is not submitted.

### Actual behavior

![image](https://user-images.githubusercontent.com/38871812/68155933-bc012380-ff18-11e9-870b-c48c329fe4a4.png)

The form is submitted.

**Comment by fraincs** [comment]
https://github.com/gsoft-inc/sg-orbit/pull/29 PR
