### ISSUE TITLE
A select item with an icon doesn't follow text / icon ratio

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#271]
### Describe the bug

![image](https://user-images.githubusercontent.com/794579/77432169-16116100-6db4-11ea-999e-27c8bdba68e4.png)

A select item icon size adapt to the select size but the text doesn't. Therefore, it breaks our standard text /icon ratio.

Available options:

- Don't adapt the icon size to the select size
- Adapt the text size to the select size

**Comment by patricklafrance** [comment]
After talking with design, we will adapt the text size to the select size

**Comment by fraincs** [comment]
So the text size will be the same as the value size?
