### ISSUE TITLE
Breadcrumb support

### ISSUE THREAD

**Issue by GateNk** [gsoft-inc/sg-orbit#272]
Dans le cadre de la nouvelle DA sur Overcast, la composante de Breadcrumb devrait éventuellement être supporté. 

Ce qui existe présentement dans l'app: 
https://overcast-stg.dev.sharegate.com/costs

Modèle légèrement modifié (à intégrer): 
https://gsoft.invisionapp.com/share/6UU5035S54C#/410623250_Breadcrumbs

En contexte: 
https://gsoft.invisionapp.com/d/#/console/18562412/386000717/preview

**Comment by patricklafrance** [comment]
@GateNk do you know when the team will need this component?

Also, at the end, is it a Select or a Dropdown menu? (Can you select a value or it's only links?)

**Comment by patricklafrance** [comment]
https://www.figma.com/file/VATs1Zu2vEXqIBicdwP3fI/Orbit---design-system?node-id=0%3A541

**Comment by GateNk** [comment]
@patricklafrance The component currently exists in Overcast, and the updated look slightly tweaks it (notably changing the arrow for a slash). The current sprint has our devs working on implementing the new art direction although they won't be touching the component anytime soon. We thought it easiest to keep what we have right now until further notice, and I've made them aware that it is in Orbit's backlog. 
![image](https://user-images.githubusercontent.com/41477329/77585674-4132a800-6ebb-11ea-8cfa-c274bf939674.png)

Hope that answers your question!

**Comment by patricklafrance** [comment]
@GateNk yes thank you :)
