### ISSUE TITLE
Checkbox should support having a basic label

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#280]
### Describe the bug

Currently a checkbox can have a "standard" label:

![image](https://user-images.githubusercontent.com/794579/77705926-53821400-6f97-11ea-8dcc-a67c2f5267d7.png)

We also need to provide a way to define a "basic" label:

![image](https://user-images.githubusercontent.com/794579/77705734-d3f44500-6f96-11ea-9208-577827fff72a.png)

**Comment by fraincs** [comment]
A basic label already exists, another kind of label could be created. Not sure about the name yet. Numeric was an option. This use case is when we need to display short text.

**Comment by patricklafrance** [comment]
Since this is very specific to a checkbox I think I would override the look of a basic label specifically for the checkbox.
