### ISSUE TITLE
Tooltip component is broken

### ISSUE THREAD

**Issue by joseph-passineau** [gsoft-inc/sg-orbit#281]
### Describe the bug

It is not possible to use the Tooltip component, it breaks to whole page. Render error.

### Steps to reproduce

```
import { Button, Tooltip } from "@orbit-ui/react-components";
import React from "react";

export const SomeComponent = () => {
    return (
        <div>
            <Tooltip content="Adds users to your feed" trigger={<Button>Add</Button>} />
        </div>
    );
};
```

### Expected behavior

Would render properly without error

### Actual behavior

The whole page crashes with multiple errors:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### Reproducible demo

N/A

**Comment by patricklafrance** [comment]
Thank for the issue @joseph-passineau.

I bootstrapped a new CRA app and the following code seems to works fine:

```
<Tooltip content="Adds users to your feed" trigger={<Button>Add</Button>} />
```

A few questions:

- What is the error? Can you paste the error and the stack trace please.
- Are you using the latest versions of `@orbit-ui/react-components`. If not, what version are you using?

**Comment by joseph-passineau** [comment]
Upgraded to the latest version and it works now.

Thanks
