### ISSUE TITLE
Button and Label padding specs should match inputs padding specs

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#293]
### Describe the bug

Input and Select padding specs have recently been updated in https://github.com/gsoft-inc/sg-orbit/issues/196. Those new padding specs should also be applied to Button and Label.

**Comment by fraincs** [comment]
Yes. In that regard, label should support compact as a variation in order to follow the button specs.

**Comment by patricklafrance** [comment]
Ok, to make sure I understand well, a label that is not compact will not comply to the same padding specs as a button?

**Comment by fraincs** [comment]
No label will follow button padding but compact will follow compact button padding which is half it's default padding.
