### ISSUE TITLE
A multiple values select should wrap when value are wider than the available space

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#298]
### Describe the bug

A multiple values select should wrap instead of taking more space when value are wider than the available space.

![multiple_values_wrap_bug](https://user-images.githubusercontent.com/794579/78079456-27d9a200-737a-11ea-81aa-5e63efbd57e8.gif)

**Comment by fraincs** [comment]
Thinking about it, I am not sure it's a bug since a dropdown's width adapts to it's content when not fluid, should't this behave the same?

**Comment by patricklafrance** [comment]
Oh ok, haven't though about that. It's not a bug then!
