### ISSUE TITLE
Brand Picker shows when there is no docs

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#30]
### Describe the bug

When a story has no doc, the brand picker is visible over the No Docs zone.

### Steps to reproduce

1. Open a chomatic story
2. Click Docs

### Expected behavior

These would not be visible.

### Actual behavior
 
![image](https://user-images.githubusercontent.com/361632/70647755-aec20d80-1c17-11ea-9c66-56b7d175a44c.png)

**Comment by samuelgaudreau** [comment]
le picker en haut à droite ne pop plus. Mais on peut le sélectionner en haut. On fix pareil?

**Comment by fraincs** [comment]
> le picker en haut à droite ne pop plus. Mais on peut le sélectionner en haut. On fix pareil?

Non comme le picker fait parti du UI global je crois que c'est ok ainsi.

**Comment by samuelgaudreau** [comment]
je te laisse la closer

**Comment by patricklafrance** [comment]
I am not sure we are talking about the same picker here.

The picker that shouldn't be visible when there is no docs is the following:

![image](https://user-images.githubusercontent.com/794579/74188967-8ce80580-4c1d-11ea-9109-ea6450a7fdf6.png)

**Comment by samuelgaudreau** [comment]
This one is already fixed. Only the global one remains =>
![image](https://user-images.githubusercontent.com/45613290/74192406-79d83400-4c23-11ea-9be2-25d2661c6ed9.png)

**Comment by patricklafrance** [comment]
Ok awesome, not sure why though.

The global one is fine, this is what Storybook calle a "tool" and this is not available when the site is published in "docs" mode (which is what we do for production docs)
