### ISSUE TITLE
Large checkbox right padding is smaller than medium checkbox

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#304]
### Describe the bug

![image](https://user-images.githubusercontent.com/794579/78592791-9ce22700-7813-11ea-8070-a4c9cdb8e100.png)

Repro in SB: http://localhost:16440/?path=/docs/components-checkbox--text#size

**Comment by fraincs** [comment]
Waiting validation as if we should scale the margin proportionally since the font size changes.
