### ISSUE TITLE
Label containing an avatar or icon should follow the padding scale

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#306]
### Describe the bug

When an avatar or icon is inside a label the label padding is not matching the defined scale.

![image](https://user-images.githubusercontent.com/361632/78596818-6c51bb80-781a-11ea-841d-20d08f47f5d9.png)

![image](https://user-images.githubusercontent.com/361632/78596832-74116000-781a-11ea-9e40-aaea56d939d9.png)

### Reproducible demo

https://sg-storybook.netlify.com/?path=/story/chromatic-select-standard--item-avatar
https://sg-storybook.netlify.com/?path=/story/chromatic-select-standard--item-icons

**Comment by patricklafrance** [comment]
I added `with-avatar` and `with-icons` to multiple values select labels. Available in master
