### ISSUE TITLE
Large date picker input selection text is hidden by the clear icon

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#308]
![image](https://user-images.githubusercontent.com/361632/78689327-379a3e80-78c4-11ea-8f23-5ed84aa3c4c9.png)

### Describe the bug

When a large date picker date is picked in certain cases the text is hidden by the clear icon due to the padding scale.

### Steps to reproduce

1. Select a date in a large date picker.

### Expected behavior

The whole date is visible.

**Comment by patricklafrance** [comment]
This problem should be solved in the input component instead of the date picker (a date picker use a read-only input component)
