### ISSUE TITLE
Add a domain for the docs website

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#31]

**Comment by fraincs** [comment]
Je suggere d'utiliser storybook.sharegate.design et orbit.sharegate.design

**Comment by patricklafrance** [comment]
Je trouve ça long à écrire et difficile à retenir?

Contre proposition: orbitui.design

**Comment by fraincs** [comment]
> Je trouve ça long à écrire et difficile à retenir?
> 
> Contre proposition: orbitui.design (orbit.design est déjà pris)

donc storybook.orbitui.design ? ou nous ne publions pas le SB?

**Comment by patricklafrance** [comment]
Je propose de conserver l'URL netlify pour le SB? Ce n'est pas un URL que nous allons partager.

Qu'en pense tu?

**Comment by patricklafrance** [comment]
@yohanb can you help us with getting the domain? Do you have super power at GSoft to make this happens?

If you have a better idea for the name, I am also interested ;)

**Comment by yohanb** [comment]
On peut en parler demain si vous voulez.  Vous ne voulez pas être sous *.sharegate.com?  Sinon faut acheter le domaine qu'on veut et faire un ajout de CNAME dans le DNS.
Le site web est hosté où?

**Comment by fraincs** [comment]
Chez Netlify
