### ISSUE TITLE
A fluid dropdown menu doesn't take all the available space

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#314]
### Describe the bug

![image](https://user-images.githubusercontent.com/794579/78797111-43016e80-7985-11ea-9609-f1ad9ffab683.png)

### Steps to reproduce

Repro in SB: ?path=/story/chromatic-dropdown-menu--fluid

**Comment by patricklafrance** [comment]
@fraincs I am not sure if we want to support this one? A fluid dropdown menu might not make sense.

**Comment by fraincs** [comment]
This indeed does not make sense. But supporting it is pretty much free.Will do.
