### ISSUE TITLE
An inline Select icon should inherit it's parents color

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#329]
### Describe the bug

![image](https://user-images.githubusercontent.com/361632/79983033-2f6e0180-8475-11ea-9880-0655eb855e90.png)

### Steps to reproduce

/?path=/story/chromatic-select-inline--item-icons

**Comment by patricklafrance** [comment]
You means the icon or the text?

**Comment by fraincs** [comment]
That's a good point. I'm not sure anymore.

**Comment by patricklafrance** [comment]
I am not sure about this, you should ask the designers.

**Comment by fraincs** [comment]
Validated, the icon should be gray
