### ISSUE TITLE
Select component logs a warning when "open" props provided

### ISSUE THREAD

**Issue by kingbaub3** [gsoft-inc/sg-orbit#340]
### Describe the bug

When provided with the "open" props, the Select logs a warning in the console.

### Steps to reproduce
Render the following component:
```
import { Select } from "@orbit-ui/react-components";

const SomeComponent = () => {
    return (
        <Select
            open
            options={[]}
        />
    );
}
```

### Expected behavior

The Select component is rendered without any warning and with its DropdownMenu opened.

### Actual behavior

The Select is rendered properly and its behavior is okay, but a warning is logged in the console.

![image](https://user-images.githubusercontent.com/6119223/81013325-f5174380-8e28-11ea-87b7-08621d6eaf15.png)

### Reproducible demo
I'm currently unable to install @orbit-ui/react in code-sandbox or stackblitz.

**Comment by patricklafrance** [comment]
Thanks for the issue @kingbaub3 

I tried the following:

```
        <Select
            options={[]}
            open
        />
```

And:

```
function Test() {
    return (
        <Select
            options={[]}
            open
        />
    );
}
```

I don't have any errors. I'm I missing something?

**Comment by patricklafrance** [comment]
Try updating to react-dom 16.13.1.

https://github.com/facebook/react/issues/18178

**Comment by kingbaub3** [comment]
It was indeed a bug with react-dom 16.13.0. I upgraded the package to 16.13.1 as described and the warning is not there anymore. 

Thanks Pat!
