### ISSUE TITLE
Add a new neutral color

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#342]
### Is your feature request related to a problem?

Yes, we need a more neutral color.

A new color need to be added. All the color CSS and foundations would need to be added.

As seen here : https://www.figma.com/file/VATs1Zu2vEXqIBicdwP3fI/Orbit-UIKit?node-id=0%3A2

**Comment by patricklafrance** [comment]
You should link to the figma page containing the new neutral palette :)
