### ISSUE TITLE
Select component not displaying provided "value" prop when dropdown opened

### ISSUE THREAD

**Issue by kingbaub3** [gsoft-inc/sg-orbit#343]
### Describe the bug

Select component not displaying provided "value" prop when dropdown opened. Instead, it displays last selected value by the user if there's one.

### Steps to reproduce

```
import { Select, selectItem } from "@orbit-ui/react-components";

const options = [
    selectItem("One", "One"),
    selectItem("Two", "Two"),
    selectItem("Three", "Three")
];

const SomeComponent = () => {
  return (
    <Select value="One" options={options} />
  );
}
```

The first time you open the dropdown, the proper value is being displayed. 
![image](https://user-images.githubusercontent.com/6119223/81225933-08a4e480-8fb8-11ea-90ec-a189004067ce.png)

Then. if you select the option "Two", the Select still displays "One" which is the expected behavior. 
![image](https://user-images.githubusercontent.com/6119223/81226060-3e49cd80-8fb8-11ea-9bf2-4b0ca6c8913a.png)

Finally, if you reopen the dropdown, the Select will display as if the option "Two" was selected, which is not the case.
![image](https://user-images.githubusercontent.com/6119223/81226187-6b967b80-8fb8-11ea-91d9-5341506a1a9d.png)

This is a simplified example to reproduce the problem. This problem may occurs in real apps when the network call to change the backend value fails. The provided "value" will not change and this problem will occur.

### Expected behavior

The provided "value" is always displayed in the Select no matter if the user selected another value.

### Actual behavior

The value selected by the user is being displayed instead of the "value" props.

**Comment by patricklafrance** [comment]
Thanks for the bug report @kingbaub3

**Comment by fraincs** [comment]
It seems that it's the current acknowledged behavior. The current design could be updated in order to show a different text color when a selection is not the current value.

**Comment by patricklafrance** [comment]
So @fraincs should I tag this as a bug? If the design doesn't work and it's confusing, IMO this is a bug or at least a feature request.

**Comment by patricklafrance** [comment]
@fraincs poke

**Comment by emilieguimond** [comment]
Hi Guys!
We have the problem on another context. On a dropdown, when you select "extra-dangerous-value", we display a modal "This will do this, do you want to continue?". If the person click "Cancel", we have the exact same result.

**Comment by patricklafrance** [comment]
We'll keep this is mind for the next version of Orbit that we are currently working on and try to make this right. For the current release of Orbit, sadly, this is a won't fix.
