### ISSUE TITLE
NumberInput arrows are misplaced when having an icon 

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#344]
### Describe the bug

![image](https://user-images.githubusercontent.com/794579/81478661-cd3f2b80-91ec-11ea-82de-25165c7e4461.png)

Repro in SB: https://sg-storybook.netlify.app/?path=/story/components-numberinput--icon

**Comment by fraincs** [comment]
Removing them seem like a sensitive and easy fix. Officevibe did that.

**Comment by patricklafrance** [comment]
Sounds good, then a NumberInput should support a Button like the TextInput. The feature have been removed since the Button was colliding with the arrows.
