### ISSUE TITLE
Infinite loading when keeping "backspace" pressed in RemoteSearchInput

### ISSUE THREAD

**Issue by PrincessMadMath** [gsoft-inc/sg-orbit#378]
### Describe the bug

You have a infinite loading spinner in the "Search Input" component when delete the search.

### Steps to reproduce

(Write your steps here:)

1. Enter 5 character to search (can be space: ' ')
2. Delete everything by keeping the backspace pressed
3. Infinite loading!

### Expected behavior

No loading when the input is empty

### Actual behavior

Infinite loading spinner 

![loading](https://user-images.githubusercontent.com/8277266/84198605-c74d9c00-aa71-11ea-9bef-6ee4e926175c.gif)

### Reproducible demo

You can repro directly on the docs: https://sg-orbit.netlify.app/?path=/docs/components-searchinput-remote--default-story

Or on storybook: https://sg-storybook.netlify.app/?path=/story/components-searchinput-remote--default-story

**Comment by patricklafrance** [comment]
Thanks for the detailled bug report!

**Comment by patricklafrance** [comment]
Fixed in next release
