### ISSUE TITLE
NumberInput Max and Min configuration does not seem to work

### ISSUE THREAD

**Issue by AlexandreArpin** [gsoft-inc/sg-orbit#394]
### Describe the bug

The example of Min/Max values for a NumberInput in the Orbit Documentation does not work.

https://orbit.sharegate.design/?path=/docs/components-numberinput--default-story#min--max

### Steps to reproduce

(Write your steps here:)

1. Visit https://orbit.sharegate.design/?path=/docs/components-numberinput--default-story#min--max
2. Min and Max are set to -5 and 5
3. Enter 9 in the NumberInput

### Expected behavior

9 is never fully inputted, it gets replaced by 5.

### Actual behavior

NumberInput allows for any numbers

![image](https://user-images.githubusercontent.com/3902349/89287581-413d7400-d622-11ea-93f7-16b24d2e7124.png)

**Comment by patricklafrance** [comment]
For the min/max this is how the native input number works, see on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

That being said, expecting some kind visual notification if the number exceed the limits seems reasonable to me. We'll see how we can add something in the reborn.

**Comment by AlexandreArpin** [comment]
Oooh I understand, it's only to pass the values to the HTML Input so that the HTML5 Form Validation can use it.

Since it's working as "intended" and not a bug, I'll close this issue, however as you noted, it'd be a nice improvement to have Orbit's validation kick in/help with the numbers inputted.
