### ISSUE TITLE
NumberInput has conflicting suggestions on how to clear the input in a controlled manner

### ISSUE THREAD

**Issue by AlexandreArpin** [gsoft-inc/sg-orbit#395]
### Describe the bug

When trying to return a NumberInput to an empty state where the placeholder is shown after having had a value in it, Orbit either warns you about invalid PropTypes or that you should be using an empty string to clear the component.

### Steps to reproduce

(Write your steps here:)

1.  `<NumberInput value={5} placeholder="%" />`
2.  `<NumberInput value={null} placeholder="%" />` gives `'value' prop on 'input' should not be null. Consider using an empty string to clear the component or 'undefined' for uncontrolled components.`
3. `<NumberInput value={""} placeholder="%" />` gives `Warning: Failed prop type: Invalid prop 'value' of type 'string' supplied to 'InnerNumberInput', expected 'number'.`

### Expected behavior
It is possible to push a value to NumberInput that will clear the component's input box to show the Placeholder.

### Actual behavior
There's no value that allow the component to show its placeholder as  a controlled component.

**Comment by patricklafrance** [comment]
> <NumberInput value={null} placeholder="%" /> gives 'value' prop on 'input' should not be null. Consider using an empty string to clear the component or 'undefined' for uncontrolled components.

Yeah this is a React input behave. We don't do much our goal is to delegate as much as possible to the original Input.

> Warning: Failed prop type: Invalid prop 'value' of type 'string' supplied to 'InnerNumberInput', expected 'number'.

I see how problematic that could be, will add "string" to the prop types in our reborn.
