### ISSUE TITLE
NumberInput does not show the step control in Latest Chrome and Edgeium

### ISSUE THREAD

**Issue by AlexandreArpin** [gsoft-inc/sg-orbit#396]
### Describe the bug
Usually, HTML5 Number Input have a little control to increase and decrease the value of the number.

In Orbit, there is a property to configure the amount by which is increases, however, the NumberInput hides the HTML5 increment/decrement control in the input.

### Steps to reproduce

1. https://orbit.sharegate.design/?path=/docs/components-numberinput--default-story#step

### Expected behavior

Either always, or when defined, the step property allow the "arrow-up" and "arrow-down" component of the html 5 number input to increase and decrease the value of the element.

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_number

### Actual behavior
The "arrow up" and "arrow down" controls is not visible.

### Reproducible demo
https://orbit.sharegate.design/?path=/docs/components-numberinput--default-story#step

**Comment by patricklafrance** [comment]
Since the behavior and look is different in browsers we choosed at the last minute to hide the arrows.

In reborn we are planning to provide custom arrows, something similar to Polaris NumberInput: https://polaris.shopify.com/components/forms/text-field#navigation
