### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by AlexandreArpin** [gsoft-inc/sg-orbit#440]
### Is your feature request related to a problem?
Currently, there's a lot of Orbit's dependencies that are out of date and breaks when trying to use Orbit with React 17.

### Describe the solution you'd like
Update Orbit's dependencies to support React 17.

### Additional context
React 17 has been out for a while now and as consumer of Orbit, we are blocked by Orbit in our upgrade path for React 17.

**Comment by patricklafrance** [comment]
The next version which will be released late february / mars will support React 17!
