### ISSUE TITLE
🚀 Test core TypeScript types

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#508]
## Description

We added a bunch of TypeScript types in the reboot. Some of them are quite complex and should offer a test suite to faciliate future maintenance.

## Checklist

Every items might not be applicable to your task. When an item is not applicable, please ✔️ the item.

- [ ] Chromatic tests
- [ ] Jest tests
- [ ] Documentation
- [ ] Figma

**Comment by alexasselin008** [comment]
To test types, this library has been recommended by https://frontendmasters.com/courses/production-typescript/

tsd: https://www.npmjs.com/package/tsd

it provides a bunch of utility function such as expectType, expectError and expectAssignable
