### ISSUE TITLE
🌟 Design the new icons in Figma

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#509]
## Checklist

Every items might not be applicable to your task. When an item is not applicable, please ✔️ the item.

- [x] Figma
- [ ] Documentation

**Comment by Chicoalvi** [comment]
Here is the [figma link](https://www.figma.com/file/VATs1Zu2vEXqIBicdwP3fI/Orbit-UIKit?node-id=8175%3A121542) to the orbit icons that need review and testing in code

Color code in Figma :

- Orange > Need test code
- Green > Approved by Designer and Front-end

**Comment by Chicoalvi** [comment]
Proposal to add the following icon orientation variations in the orbit library:
Arrow
Caret
Chevron

**Comment by fraincs** [comment]
> Proposal to add the following icon orientation variations in the orbit library: Arrow Caret Chevron

These are not necessary for us but they could be used internally in Figma since rotating icons in Figma leads to weird glitches.

**Comment by alexasselin008** [comment]
Inactive issue, doesnt track anything, will close
