### ISSUE TITLE
💡  Single variant icons library

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#511]
## Description

Our currently icons library rely on 2 variants (24x24 and 32x32) to elegantly support small & large size. This is a problem because some our components requires the icon to dynamically adapt to the current font-size (`1em`) and therefore we can't know which variant of the icon should be used.

To solve the problem we want to develop a new single variant icons library based on `stroke` like https://phosphoricons.com/

## Specifications

- Support 12x12, 16x16, 20x20, 24x24, 32x32, 40x40.
- Support Mac & Windows OS

## Related issues

- [x] Design icons (https://github.com/gsoft-inc/sg-orbit/issues/509)
- [ ] Add icons to Orbit (https://github.com/gsoft-inc/sg-orbit/issues/510)

**Comment by patricklafrance** [comment]
Seems obsolete to me. What do you think @fraincs ? Should this issue be closed?

**Comment by fraincs** [comment]
We are working on a variation of this issue right now. I will close this issue by opening the new issue and referring to this one.
