### ISSUE TITLE
❗   Documentation should follow Orbit space theme.

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#520]
## Description

Orbit documentation should use Space wording as well as icons. No reference to a Sharegate Product / Tagline / Icon should be used in our documentation and Chromatic Tests.

## Specifications

- All icons are spaced themed.
- All texts are spaced themed.

## Related issues

- #518 - Documentation texts should be Space themed
- #519  - Documentation icons should be Spaced themed

**Comment by patricklafrance** [comment]
I feel like this will never happened. I suggess closing this issue. What do you think @fraincs ?

**Comment by fraincs** [comment]
It's coming with the revamp of the icons, the space icons are ready (4 of them) this could be closed and added to the icon revamp story.

**Comment by alexasselin008** [comment]
@fraincs This is a duplicate of https://github.com/gsoft-inc/sg-orbit/issues/519 now that the other issue is done
