### ISSUE TITLE
🌟 Add Do's & Don’t's to components documentation

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#524]
## Description

Most of Orbit components lack context about when to be used and when not to be used. Adding more context would greatly benefits our developers (and even our designers).

Inspiration:

- [Spectrum](https://spectrum.adobe.com/page/button/#Usage-guidelines)
- [Twilio](https://paste.twilio.design/components/alert#when-to-use-an-alert)

## Checklist

TBD - list all components and checkbox those which are done

**Comment by Chicoalvi** [comment]
### Documentation nomenclature decided by the design team
<img width="280" alt="Capture d’écran, le 2021-04-29 à 11 18 20" src="https://user-images.githubusercontent.com/16927274/116576024-2fe97580-a8dd-11eb-8dd1-4af22cfebe2c.png">
