### ISSUE TITLE
🚀  Swap Calibre for TT Interphase in all Components

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#532]
## Description

Phasing Out Calibre means adapting all components for the smaller, more standard, size of TT Interphase. Every components need to be validated, especially Typographic related components(Paragraph, Heading, Text).

## Checklist

Every items might not be applicable to your task. When an item is not applicable, please ✔️ the item.

- [ ] Chromatic tests
- [ ] Documentation

**Comment by patricklafrance** [comment]
Numbers looks quite different:

Now:
![image](https://user-images.githubusercontent.com/794579/117189927-c241bb80-adac-11eb-90aa-e246fa03b721.png)

Before:
![image](https://user-images.githubusercontent.com/794579/117189963-cd94e700-adac-11eb-82ae-4a080f10b1d8.png)

**Comment by GateNk** [comment]
Ouais c'est normal que les O et 0s dans TT Interphases soient légèrement plus bombés!
![image](https://user-images.githubusercontent.com/41477329/117190148-1056bf00-adad-11eb-8d8f-d472aa2e1cb7.png)

Moi je trouve ça clean comme transition!

**Comment by patricklafrance** [comment]
It seems like everything if more compact & lighter? It's harder to visualize, for example:

Now (https://6092dd1c0217f100ca5b7304--sg-storybook.netlify.app/?path=/story/field--input):
![image](https://user-images.githubusercontent.com/794579/117190271-35e3c880-adad-11eb-95e6-21b307ec4595.png)

Before(https://sg-storybook.netlify.app/?path=/story/field--input):
![image](https://user-images.githubusercontent.com/794579/117190325-485e0200-adad-11eb-8c87-ed27c23c5b58.png)

**Comment by GateNk** [comment]
Indeed, TT seems slightly wider and shorter, and lighter too! But that may be our eyes playing tricks on us :P The mapping was also set the closest equivalents to what we had before, but Calibre was such an oddity that almost everything had to be lowered by 2 points. 

![image](https://user-images.githubusercontent.com/41477329/117193172-8d376800-adb0-11eb-81a1-c9093ab8d215.png)

**Comment by fraincs** [comment]
> I do feel like everything is more compact & lighter? It's harder to visualize, for example:
> 
> Now (https://6092dd1c0217f100ca5b7304--sg-storybook.netlify.app/?path=/story/field--input):
> ![image](https://user-images.githubusercontent.com/794579/117190271-35e3c880-adad-11eb-95e6-21b307ec4595.png)
> 
> Before (https://sg-storybook.netlify.app/?path=/story/field--input):
> ![image](https://user-images.githubusercontent.com/794579/117190325-485e0200-adad-11eb-8c87-ed27c23c5b58.png)

![image](https://user-images.githubusercontent.com/361632/117193164-8b6da480-adb0-11eb-90d1-ca5a4e992cf3.png)
Interphase is indeed on the shorter side, we could add letter spacing but this would be a "fix", or could learn to embrace how this font is and adapt, and in some circumstances use a higher font size like for messages under an input.

**Comment by patricklafrance** [comment]
Sounds good @fraincs . As long as things are visually accessible I am fine with it.

For this particual usecase, maybe we should consider a darker color for the field description?

**Comment by fraincs** [comment]
> Sounds good @fraincs. As long as things are visually accessible I am fine with it.
> 
> For this particual use case, maybe we should consider a darker color for the field description?


we could go the primary text way (Marine 900) 
 @GateNk thoughts?

**Comment by GateNk** [comment]
> > Sounds good @fraincs. As long as things are visually accessible I am fine with it.
> > For this particual use case, maybe we should consider a darker color for the field description?
> 
> we could go the primary text way (Marine 900)
> @GateNk thoughts?

Yeah, that would work! Contrast issues will hopefully be resolved when we move towards a semantic & accessible palette

**Comment by fraincs** [comment]
> > Sounds good @fraincs. As long as things are visually accessible I am fine with it.
> > For this particual use case, maybe we should consider a darker color for the field description?
> 
> we could go the primary text way (Marine 900)
> @GateNk thoughts?

![image](https://user-images.githubusercontent.com/361632/117335199-e06cf180-ae68-11eb-83ea-2a6fa8be2feb.png)

What do you think about marine 500 finally?

**Comment by GateNk** [comment]
> > > Sounds good @fraincs. As long as things are visually accessible I am fine with it.
> > > For this particual use case, maybe we should consider a darker color for the field description?
> > 
> > 
> > we could go the primary text way (Marine 900)
> > @GateNk thoughts?
> 
> ![image](https://user-images.githubusercontent.com/361632/117335199-e06cf180-ae68-11eb-83ea-2a6fa8be2feb.png)
> 
> What do you think about marine 500 finally?

Approved!

**Comment by fraincs** [comment]
This issue is set as stale as merging it would mean making a breaking change release. This issue is missing some design review too.

**Comment by fraincs** [comment]
Fixed in 2021-06-01 release
