### ISSUE TITLE
🌟  Animation in Orbit should be standardized

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#537]
## Description

While Orbit has a set of reusables values, from typographic scale to colors, no values have been determined for our animation variables. Exploration and decisions have to be made in order to facilitate the animation decisions. Val Head has a great process on how to achieve this, this is the recommended path.

As a reminder animations are not only the icing on the cake:
- Motion can provide context and information without requiring action such as additional clicks.
- Motion can capture attention and highlight an important piece of data or key UI element.

## Checklist

- [ ] Figma
- [x] Documentation

**Comment by patricklafrance** [comment]
Is it done @fraincs ? Is there something to add to Figma?

**Comment by fraincs** [comment]
Late reply @patricklafrance I think Figma could be updated now that I think we can add "animation" in Figma. Values could be exposed in an Animation page too.

**Comment by fraincs** [comment]
Figma is updated in the Motion tab.

**Comment by patricklafrance** [comment]
Is there any other issue to offer to our dev teams components to easily use standardized animations?

This is one thing to standardized animations values but I doubt this is the right distribution format for our teams. Should be components like FadeIn, FadeOut etc.. Maybe hooks?! I don't know. But something more with a better dev ux than tokens.

**Comment by patricklafrance** [comment]
@fraincs yes this is my question/request, make sure you don't forget to create one since you closed this one.

**Comment by fraincs** [comment]
https://github.com/gsoft-inc/sg-orbit/issues/960 issue has been started
