### ISSUE TITLE
🐛 Checkbox should forwardRef HTMLInputElement instead of element

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#540]
## Describe the bug

No bug, just an observation. Also, the property onCheck seems to be used in the code, but it not available through the interface. It is not supported in HTMLInputElement also

**Comment by patricklafrance** [comment]
This is intended. It's been standardized to always forward the ref of outer most element. If there are use cases we might revisit this decision.

`onCheck` is only intended to be used when a `CheckableContext` is defined.
