### ISSUE TITLE
🐛 ThemeProvider's typings should be improved

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#541]
## Describe the bug

setColorScheme accepts a ColorScheme, it should accept ColorSchemeOrSystem. Also, all the property should not be optional. A  better defaultValue should be provided

Before : 
```
export interface ThemeContextType {
    theme?: Theme;
    colorScheme?: ColorScheme;
    setColorScheme?: (newColorScheme: ColorScheme) => void;
}
```

After: 
```
export interface ThemeContextType {
    theme: Theme;
    colorScheme: ColorScheme;
    setColorScheme: (newColorScheme: ColorSchemeOrSystem) => void;
}
```

**Comment by patricklafrance** [comment]
I don't agress with removing the optional theme and colorScheme, default values should be provided instead.

theme -> "apricot"
colorScheme -> "light"

**Comment by alexasselin008** [comment]
@patricklafrance we do pass default values to the ThemeProvider itself 
```
<ThemeProvider colorScheme="light" defaultColorScheme="light" theme="apricot">
```

However, when we consume the 
```
    const { colorScheme, setColorScheme } = useThemeContext();
```

it says setColorScheme might be undefined, wich does not make sense

**Comment by alexasselin008** [comment]
If you meant to provide default values to the context, i've added a comment here if you want to talk about it : 
https://github.com/gsoft-inc/sg-orbit/pull/542/files#r618750017

**Comment by patricklafrance** [comment]
Confused the Context with the Component sorry!
