### ISSUE TITLE
❗ Allow validationState to accept a boolean

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#590]
## Description

At first glance, validationState accepting "valid" and "invalid" is nice. It future proofs a little bit if we want to allow more states one day. However, in our codebase, it translate to the same pattern everytime : 

```
validationState={hasError ? "invalid" : "valid"}
```

I would suggest either : 
1- Change the "valid" | "invalid" values to a boolean
2- Provide a richer type, like the autofocus props. validationState could be "valid" | "invalid" | boolean. This way, it stays future proof, but translate in cleaner code for the clients in the meantime

**Comment by patricklafrance** [comment]
I am not sure I see the point of this. API is all about make choices and decisions. In this case the decision is to accept an explicit state. Adding a boolean choice kind of break this.

I don't think this is that big of an overhead from a consumer standpoint to convert a boolean to a string.

**Comment by alexasselin008** [comment]
I agree that an API is all about making choices and decisions. In this context, i would argue that that decision might not be the best one and thats what i'm trying to discuss here.  I'm bringing this discussion to you because its the first thing Laurent and I are flagging as a pain point when migrating our code. Even if it is "not that big of an overhead from a consumer standpoint", it can be removed with what appears to be no downsides.  

I know that is the pattern that is used in React-Spectrum, but other libraries like Chakra and Carbon use an isInvalid props. At the end of the day, if we decide not to change it, we will make an helper method that will be `getValidationState(boolean): string` and we will use it when we need it. So nothing urgent and nothing broken.

I would appreciate however if you could describe a bit this decision, so when can relay this informations to the other developpers when they ask us.

**Comment by patricklafrance** [comment]
This decision have been made around the same time we switched our variant/shape/color props to strings instead of booleans. 

The idea is to avoid boolean props when we supect we might need to add additional values in the future and avoir making a future breaking change.
