### ISSUE TITLE
❓ Including a search within a TagsPicker

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#593]
In Orbit v1, we had the option to search through the elements of a `TagsPicker`.
This has been removed from Orbit v2 but we'd like to implement it on our side.

We tried with the `SearchInput` and `Autocomplete` for differrent options but it looks like when using `MenuTrigger` and `Menu` to build the TagsPicker, we can't use an input field inside of the `Menu`.

Implementation from Orbit v2: https://orbit.sharegate.design/?path=/docs/tag--default-story#tags-picker

Would there be a way to allow for a `SearchInput` inside of the `Menu`?

**Comment by patricklafrance** [comment]
Hey!

You can provide whatever you want as the second child of `<MenuTrigger>` so in theory you can.

You could develop a new component which would wrap the existing `<Menu>` component and add a search functionnality.

It hasn't been thought for this though so you might encounter limitations and endup depending on using internals which could breaks. 

I wonder why you would do this? It's been discussed that the TasgPicker would drop the search feature and every one was fine with it.

**Comment by alexasselin008** [comment]
"I wonder why you would do this? It's been discussed that the TasgPicker would drop the search functionnality and everyone was fine with it"

We were not aware of that. Thank you
