### ISSUE TITLE
🐛 Missing props in SearchInput's interface

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#598]
## Describe the bug

Search input is missing the following properties : 
```
    button?: ReactElement<...>;
    readOnly?: boolean;
    id?: string;
```

## Steps to reproduce

```
<SearchInput button={<CrossButton aria-label="Clear value" />} placeholder="Where to?" />
```

## Expected results

typescript should allow this

**Comment by patricklafrance** [comment]
Oops.

Sounds good except for `button`. The main feature of a `<SearchInput>` is to natively display a clear button on hover. Allowing a consumer to render a second button doesn't make much sense.

I was thinking today that maybe we should have a comon `InputProps` interface share between all our forms component. I wonder which props they might all have in common and if it worths it.

**Comment by alexasselin008** [comment]
Did not notice the hover effect, good point

**Comment by patricklafrance** [comment]
@alexasselin008 since SearchInput typings "extends" an input, shouldn't it have `readOnly` "by default" ?

```
export const SearchInput = forwardRef<InnerSearchInputProps, "input">((props, ref) => (
    <InnerSearchInput {...props} forwardedRef={ref} />
));
```

As you can see on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly), `readonly` is a native property of an input
