### ISSUE TITLE
🚀 TextLink should be accessible

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#599]
## Description

TextLink are indiscernible from standard text when surrounded by text. This issue aims to fix this, by setting a new sensible default.

A decision has to be made as to what is the default (underlined or dotted) as well as a name for a no underline textLink, quiet could be a great name.

## Checklist

- [x] Chromatic tests
- [x] Documentation
- [ ] Figma

**Comment by fraincs** [comment]
Here is what I suggest

- isQuiet : bool when a link has no underline in it's default state
- add an OverBackground prop that would be sort of an inverted link (white) for cases where the links are over a background.
- default to an underline link, dotted would be supported via the underline prop with a value of dotted

**Comment by patricklafrance** [comment]
I don't think a TextLink should be that much configurable (adding 2 props like this). Doing so, is a patch instead if taking time to establishing clear guidelines about how we should use links in our apps.

Furthermore, `isQuiet` in Spectrum is a not a link prop, it's ThemeProvider mode which affect all component when set, I don't it should be added to a specific component.

**Comment by fraincs** [comment]
> I don't think a `<TextLink>` should be that much configurable (adding 2 props like this). Doing so, is a patch instead of taking time to establish clear guidelines about how we should use links in our apps.
> 
> Furthermore, `isQuiet` in Spectrum is a not a prop of their Link component, it's a ThemeProvider variant which affect all components when set. I don't think it should be added to a specific component.

Good point concerning the isQuiet, this make sense then.

I agree that we should choose between dotted and underlined and provide a accented link that could be not underlined.

**Comment by fraincs** [comment]
> I suggest having two types of Text links:
> The first one would be basic and classic, one line below the text without any other particularity.
> 
> The second one would also be very basic with a line below the text. The whole would be of a colour like Apricot500. The goal is to have a catchy text link option.
> 
> Finally, I suggest to slowly move towards microanimation with this practical "easy" topic by proposing this https://codepen.io/aaroniker/pen/VwjexVy

This micro animation seems more like a macro animation. This could work in a marketing website but would make our app look childish. I agree with two textLinks one standard and one with the app main color.

**Comment by GateNk** [comment]
If we go by the logic that a link within a body of text must have an underline, and a floating link mustn't, I think it works. Both should still show an underline when hovered at the very least. 

And I think dotted underlines are another pattern entirely as they allow the presentation of UI elements without leaving the page (e.g. tooltips). I wouldn't use them for general links. Imo!

**Comment by fraincs** [comment]
> Right now we have an `underline` prop allowing `"solid"` and `"dotted"` value. When it's specified, the default state of a `<TextLink>` will display a text decoration matching the specified underline value.
> 
> Maybe we could extend underline to `"none"`, `"solid"` and `"dotted"` with a default value of `"solid"` ?
> 
> I was thinking about maybe switching this to a "variant" prop instead but then it's limiting if we want to add support for "overBackground" since it wouldn't allow combining "overBackground" and an underline style.
> 
> Do we have actual use cases for "overBackground" ?
> 
> I am in for this if the guidelines described by @GateNk are formalized to ensure we keep consistant UI and it's not subjective. Should it be added to our Figma documentation? Our Storybook documentation? Somewhere else?

extending the underline has my vote

I don't have a case on hand for an overBackground it was a suggestion, could be added down the line if needed.

**Comment by fraincs** [comment]
fixed with https://github.com/gsoft-inc/sg-orbit/pull/614
