### ISSUE TITLE
🐛 Alert's icon size is too small when Alert's width is restricted

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#610]
## Describe the bug

Currently, in Apricot : 
![image](https://user-images.githubusercontent.com/38871812/118019039-8667a280-b326-11eb-93f9-d1c6187b5d1e.png)

## Steps to reproduce

Reproductible in Orbit's documentation
```
<WarningAlert style={{width:"440px"}}>
    <Content>Resolving the mismatch will remove guests from groups where the setting becomes more restrictive or changes from allowed to not allowed.</Content>
</WarningAlert>
```

## Expected results

I would expect the icon to be the same size as before and the text should wrap more.

**Comment by patricklafrance** [comment]
@fraincs 😆

**Comment by fraincs** [comment]
> @fraincs 😆

On it.

**Comment by fraincs** [comment]
Fixed with https://github.com/gsoft-inc/sg-orbit/pull/612
