### ISSUE TITLE
🐛 SearchInput and Formik

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#623]
## Describe the bug

I created a Formik Wrapper around a SearchInput.
The current behavior is that when i press enter, the form submits. There was no "Clear" option before.

When using the new SearchInput, the clear option does not work. After some debugging, i found that the Formik's onChange handler expects a ChangeEvent from the HTMLInputElement, and retreive the "name" and "value" from it. However,when pressing the clear button, the event passed to the onChange handler is a ButtonClick, so formik does not have a reference to the HTMLInputElement, and can't change the value.

The workaround i found was to add a onClear method to my FormikSearch, and trigger the right handler like this :
```
    const handleChange = (event: SyntheticEvent, value: string) => {
        if (event.type === "click") {
            setFieldValue(name, value);
            onClear(event);
        } else {
            onChange(event);
        }
    };
```

my usage looks like this : 
```
            {({ values, submitForm }) => (
                <Form className="flex items-center">
                    <div className="mr7">
                        <FormikSearch
                            name="searchInput"
                            className={styles.searchBar}
                            value={values.searchInput}
                            placeholder="Search"
                            onClear={() => {  <--- Je submit le form quand on clear
                                submitForm();
                            }}
                        />
                    </div>
```

I believe the onChange method should not receive a ButtonClick event from the button.

**Comment by patricklafrance** [comment]
Orbit components custom handler shouldn't use native handler names. For the SearchInput, a onValueChange handler should be added.

Furthermore, an additional onClear handler should be considered.
