### ISSUE TITLE
🐛 Accordion's variant should have an optional typing

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#625]
## Describe the bug

![image](https://user-images.githubusercontent.com/38871812/119035058-2784d780-b97d-11eb-848b-acbae9d5672d.png)

According to the documentation, that property is optional. However, it is declared as required in the interface 

```
export interface InnerAccordionProps extends DomProps {
    /**
     * The type of expansion that is allowed.
     */
    variant: "borderless" | "contained";
```

should be

```
export interface InnerAccordionProps extends DomProps {
    /**
     * The type of expansion that is allowed.
     */
    variant?: "borderless" | "contained";
```

**Comment by patricklafrance** [comment]
@fraincs great learning here :)

**Comment by fraincs** [comment]
> @fraincs great learning here :)

yup will work on this soon.
