### ISSUE TITLE
❗ Tag variant ghost?

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#626]
## Description

This issue may be silly, but i wanted to have your opinion on this.

![image](https://user-images.githubusercontent.com/38871812/119037727-581a4080-b980-11eb-9c2c-18f4691e03cb.png)

In this image, the legend at the bottom. 

Would you use 
```
<div>
    <Dot className="mr2" color="--o-ui-alias-primary-500" />
    <Text>Falcon 9</Text>
</div>
```

```
<Tag variant="ghost">
    <Dot color="--o-ui-alias-primary-500" />
    <Text>Falcon 9</Text>
</Tag>
```

**Comment by patricklafrance** [comment]
In this case, for me, it's not a tag, it a dot with a label

```
<Dot color="--o-ui-alias-primary-500">Falcon 9</Dot>
```
