### ISSUE TITLE
Add an Introduction page to the Docs

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#64]
The home page of Orbit Docs is currently the packages page, an Introduction page could be implemented in order to introduce Orbit-UI to new comers.

**Comment by patricklafrance** [comment]
Sure but make sure that we have something usefull to write in that page. The one in our old docz documentation wasn’t really usefull.

**Comment by fraincs** [comment]
> Sure but make sure that we have something usefull to write in that page. The one in our old docz documentation wasn’t really usefull.

Indeed this is something that will be taken care of post Xmas

**Comment by patricklafrance** [comment]
Maybe have a section that talks about box-sizing, like Bootstrap: https://getbootstrap.com/docs/4.4/getting-started/introduction/#box-sizing

Maybe something more like this? https://reaviz.io/?path=/docs/docs-intro--page

**Comment by patricklafrance** [comment]
Ideas:

Emie:

À mon avis, c'est un outil qui nous permet d'unifier nos efforts créatifs, un outil de référence pour tout ceux qui travaillent à créer des expériences visuelles (autant produits que marketing et brand) au sein de ShareGate (designers, devs, copywriters)  et un outil qui nous permet de gagner du temps.

Pat:
J'ajouterais aussi qui nous permet d'assurer une consistance visuelle à travers toutes nos expériences visuelles

From a blog post:
From a business perspective, a design system serves as a strategy of increasing productivity by avoiding redesign and redevelopment. It’s a set of toolkit used for facilitating customer-oriented development to meet business requirements. On the product side, a design system unifies the product experience by providing company-specific visual standards and pixel-perfect patterns in live code.

**Comment by patricklafrance** [comment]
https://www.lightningdesignsystem.com/guidelines/overview/
