### ISSUE TITLE
❓ Nested Text for emphasis?

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#644]
Hi, 

We had a use case that is fairly common that is 
```
<span>
This team/group has been <span className="fw7">inactive for the past {inactiveGroupsThresholdDays} days</span>, which raises the question — what shall we do with it?
</span>
```

Should we convert it to
```
<Text size="lg" className="f6 tc lh4 mb6 marine-100 fw5">
This team/group has been <Text size="lg" className="fw7">inactive for the past {inactiveGroupsThresholdDays} days</Text>, which raises the question — what shall we do with it?
</Text>
```

or 
```
<Text size="lg" className="f6 tc lh4 mb6 marine-100 fw5">
This team/group has been <span className="fw7">inactive for the past {inactiveGroupsThresholdDays} days</span>, which raises the question — what shall we do with it?
</Text>
```

**Comment by fraincs** [comment]
I would rather do 

```
<Paragraph>
This team/group has been <Text>inactive for the past {inactiveGroupsThresholdDays} days</Text>, which raises the question — what shall we do with it?
</Paragraph>
```

which makes me wonder if an emphasis prop on Text is something we would like to see?

**Comment by LaurentDario** [comment]
I can see cases where there would be an emphasis on a non-paragraph text.
Also the thing that I find a little tricky is that it forces us to redeclare the size of the Text for the emphasis to avoid it being re-sized to the default size.

**Comment by fraincs** [comment]
> I can see cases where there would be an emphasis on a non-paragraph text.
> Also the thing that I find a little tricky is that it forces us to redeclare the size of the Text for the emphasis to avoid it being re-sized to the default size.

Do you think that an emphasis component would work? It would have a font size inherit in order to redeclare size.

**Comment by patricklafrance** [comment]
@LaurentDario it's because we aim to stop providing a default body font-size to improve encapsulation therefore a Text component comes with a font-size by default instead of inheriting it's parent font-size.

**Comment by LaurentDario** [comment]
I like the idea of size="inherit" personally but open to suggestions!

**Comment by patricklafrance** [comment]
What's the status of this question? Should we update something in Orbit?
