### ISSUE TITLE
🐛 Multivariant size docs example is broken

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#655]
## Describe the bug

2xs, xs, sm & md sizes all render as 24x24, they should be different.

![image](https://user-images.githubusercontent.com/794579/121402506-f8cca200-c927-11eb-9e7d-33006ac69fff.png)

**Comment by fraincs** [comment]
Upon inspection it seems that multivariant icons always render the class `o-ui-icon-md` as well as their size class.
