### ISSUE TITLE
❗ Add documentation to Text/Heading/Paragraph components

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#657]
## Description

When migrating our codebase with these new components, we realized we really need a documentation that maps a component's size to our typography guidelines. For instance, if we have a `<span className="f7 lh4 fw6" >` we need to know that this translates to `<Text size="md" className="fw6" >`

I would suggest a table like in the [Typography documentation page ](https://orbit.sharegate.design/?path=/docs/typography--page#headlines).

Header

Size | Font Size | Line Height |  &nbsp;
-- | -- | -- | --
xs | f9 | lh1 | That’s one small step for man,one giant leap for mankind.
sm | f8 | lh2 | That’s one small step for man,one giant leap for mankind.
md | f7 | lh4 | That’s one small step for man,one giant leap for mankind.

Paragraph

Size | Font Size | Line Height |  &nbsp;
-- | -- | -- | --
xs | f9 | lh1 | That’s one small step for man,one giant leap for mankind.
sm | f8 | lh2 | That’s one small step for man,one giant leap for mankind.
md | f7 | lh4 | That’s one small step for man,one giant leap for mankind.

Text 

Size | Font Size | Line Height |  &nbsp;
-- | -- | -- | --
xs | f9 | lh1 | That’s one small step for man,one giant leap for mankind.
sm | f8 | lh2 | That’s one small step for man,one giant leap for mankind.
md | f7 | lh4 | That’s one small step for man,one giant leap for mankind.

**Comment by fraincs** [comment]
I am not sure about adding Component reference in the foundation section as Components come and go while our foundations should not change. Thoughts?

**Comment by alexasselin008** [comment]
The documentation could be in a different section than Foundation and Component. I've look a couple of design system, and Material UI has a section named "Guides" with a couple example of how to implement certain features. I'm thinking we could do something like that for this

**Comment by alexasselin008** [comment]
Or if we want, it could directly be in the Text component's documentation. So component refers to the foundation, but not the other way around

**Comment by fraincs** [comment]
@patricklafrance I remember a discussion where you were against this way of doing things, would that be ok for you?

> Or if we want, it could directly be in the Text component's documentation. So component refers to the foundation, but not the other way around

**Comment by patricklafrance** [comment]
Yeah not a fan of duplicating all this info in the component pages. 

I am also not a big fan of keeping a sync of the whole sizing info with the new sizing info.

Since we now refer to the size of our text with t-shirt size instead of f1, f2, f3 and all the codebase have been migrated to t-shirt sizes, I don't see the point.

The only reason I can imagine is because the designs in Figma still use f1, f2, f3 ... I would suggest to make the change there instead.

![image](https://user-images.githubusercontent.com/794579/121547782-7355fa00-c9da-11eb-9d4b-0df6a3f915ca.png)

This is customizable and could be t-shirt sizes instead.

**Comment by patricklafrance** [comment]
Couldn't they only updates the new designs?

**Comment by alexasselin008** [comment]
My bad, that is what i meant by all. All the design of upcoming features

**Comment by patricklafrance** [comment]
Let us know how your conversation goes, if they can't do it quickly, we will add a temporary migration section.
