### ISSUE TITLE
🐛 Tabs Component : onSelectionChange called multiple times on tab change

### ISSUE THREAD

**Issue by laurentfrenette** [gsoft-inc/sg-orbit#658]
## Describe the bug

On the [Tabs](https://orbit.sharegate.design/?path=/docs/tabs--default-story) component, onSelectionChange handler is called multiple times whenever you change tab **once**.

## Steps to reproduce
1 - Go to https://orbit.sharegate.design/?path=/docs/tabs--default-story#default

2 - Replace the default editable example with the following code : 

`<Tabs aria-label="Planets" onSelectionChange={e => console.log(e)}>
    <Item key="mars">
        <Header>Mars</Header>
        <Content>Mars is the fourth planet from the Sun and the second-smallest planet.</Content>
    </Item>
    <Item key="jupiter">
        <Header>Jupiter</Header>
        <Content>
            Jupiter is the fifth planet from the Sun and the largest in the Solar System.
        </Content>
    </Item>
    <Item key="venus">
        <Header>Venus</Header>
        <Content>
            Venus is the second planet from the Sun. It is named after the Roman goddess of love and
            beauty.
        </Content>
    </Item>
</Tabs>`

3 - Open the devtool console and change tab on the default example.

## Expected results

onSelectionChange is called only once.

**Comment by alexasselin008** [comment]
Also, clicking on an already selected tab cause a onSelectionChange trigger, even if the selection has not changed
