### ISSUE TITLE
🚀 Listbox & Menu description are not accessibile

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#666]
## Description

For me, the following description is too small, and the text color contrast might also be to small. It seems exhacerbed since we updated our font.

![image](https://user-images.githubusercontent.com/794579/122104884-24e39980-cde6-11eb-9a3d-bf0fde1662b0.png)

## Checklist

- [x] Chromatic tests
- [x] Documentation
- [ ] Figma

**Comment by fraincs** [comment]
I don't think we can bump the text size as it would match the title size, the hierarchy would be gone as both items would have the same visual impact. A colour change could work.
