### ISSUE TITLE
🚀 Field "help message" are not accessible

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#667]
## Description

For me, the following description is too small, and the text color contrast might also be to small. It seems exhacerbed since we updated our font.

![image](https://user-images.githubusercontent.com/794579/122104995-4775b280-cde6-11eb-9288-ec558bd50bd6.png)

## Checklist

- [x] Chromatic tests
- [x] Documentation
- [ ] Figma

**Comment by patricklafrance** [comment]
Zendesk garden keep the same font-size for the description but play with the color contrast:

![image](https://user-images.githubusercontent.com/794579/122124793-c1656600-cdfd-11eb-8132-71e3b2b3578c.png)

**Comment by fraincs** [comment]
They are the same size but I think `sm` is too small I will bump the label and the message to `md`.
