### ISSUE TITLE
🐛 Tooltip does not support break-word

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#668]
While implementing the `TooltipTrigger` component, we noticed that in case of URLs displayed inside of the `Tooltip`, the limited width of the tooltip makes it so that the copy bleeds out of the component (for example, in the Copy To One Drive modal).

## Describe the bug

For long copy with no spaces (like URLs), the copy doesn't break and bleeds out of the Tooltip

## Steps to reproduce

This is reproducible inside of the Orbit documentation, under TooltipTrigger.
Remove spaces in the copy of the Tooltip.

![image](https://user-images.githubusercontent.com/234418/122109554-7fcbbf80-cdeb-11eb-8c7a-16ae2012c84d.png)

## Expected results

The copy should still break inside of the Tooltip.
This has been achieved in the Copy To One Drive modal by adding `overflow-wrap: break-word` on the `Text` component inside of the Tooltip.

**Comment by patricklafrance** [comment]
Thanks for the issue. By the way, I doubt adding an URL in a tooltip is a good idea ;)

**Comment by LaurentDario** [comment]
I can see the interest of the tooltip to indicate the folder that is being copied in the process here:
![image](https://user-images.githubusercontent.com/234418/122122136-654d1280-cdfa-11eb-9cbc-c3bd3a0b8bc6.png)

**Comment by patricklafrance** [comment]
Meh, I would rather use an item description:

![image](https://user-images.githubusercontent.com/794579/122123611-2e77fc00-cdfc-11eb-91b4-fa5bb11b63ca.png)

https://orbit.sharegate.design/?path=/docs/autocomplete--default-story#item-description

**Comment by patricklafrance** [comment]
The item description might be a bad idea since we don't controle the length of these links and they might end up multiline if we use the item description. Oh well!
