### ISSUE TITLE
❗ Add support for conditional rendering in Menu, List,... component

### ISSUE THREAD

**Issue by PrincessMadMath** [gsoft-inc/sg-orbit#680]
## Description

Component that expect list of component does no support conditional rendering (https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator - which return {false} when the predicate is not respected). When you try to open the menu there is a "TypeError: Cannot read property 'type' of null". 

The requested behavior would that the component simply ignore this type of component.

### Code exemple

You can try this out here: https://orbit.sharegate.design/?path=/docs/menu--default-story

```
<MenuTrigger>
    <IconButton color="secondary" aria-label="View tasks">
        <VerticalDotsIcon />
    </IconButton>
    <Menu>
        <Item key="launch">Launch...</Item>
        {false && <Item key="eject">Eject...</Item>}
        <Item key="land">Land...</Item>
        <Item key="help">Help</Item>
        <Item key="exit">Exit</Item>
    </Menu>
</MenuTrigger>
```

**Comment by PrincessMadMath** [comment]
There is possibly more component that does not support conditional rendering.

**Comment by patricklafrance** [comment]
Thanks for the issue @PrincessMadMath! I'll see what I can do to support condition rendering.
