### ISSUE TITLE
🐛 DateInput triggers onDateChange even if date doesn't meet the min/max requirement

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#683]
It seems that the latest update to Orbit, fixing the `onDateChange` calls, introduced a new bug where `min` and `max` are ignored before sending the `onDateChange` event.

## Describe the bug

If you enter a date that is not respecting the limitation of the `min` or `max` props, the `onDateChange` gets called once before updating the date to that limit.

## Steps to reproduce

Reproducible on the Orbit documentation, under `DateInput`:
![image](https://user-images.githubusercontent.com/234418/122817027-6b813a00-d2a5-11eb-89b8-d4ffe9a8cd1f.png)
Test was run inputting 02-06-2021 in a field with `min` set at `new Date()` (being 21-06-2021), the console log inside of the `onDateChange` gets triggered for both the inputted date and the min date.

## Expected results

`onDateChange` should only trigger for the `min` date.

**Comment by patricklafrance** [comment]
Hey Laurent. thanks for the issue.

This is as expected. We updated the min/max date behavior to "clamp" only on blur. Therefore `onDateChange` is called everytime the date change, even if it doesn't match the min/max thresholds.

The value will be clamped once on blur occurs (onDateChange is called before the `onBlur` event handler to ensure you get the right value if you save on blur).

**Comment by LaurentDario** [comment]
So if I understand well, we should handle the min/max value inside of the `onDateChange` to make sure it doesn't go through with the wrong value?

**Comment by patricklafrance** [comment]
I doubt so, once the user move the focus out of the date input, the value will be clamped automatically to match the min/max threshold and `onDateChange` will be called with the clamped value. We did this because it was weird to automatically modify the value while the user is still typing.

Do you have a specific use case for which this behavior doesn't work?

**Comment by LaurentDario** [comment]
In the demo from the doc that I posted, `onDateChange` is being called before the Blur, as soon as the date is fully entered.
In Apricot, you can see it happen on the Settings / Categorization page, at the very bottom. If you input a date, it sends the request to change the date with the wrong date and returns en error from the API, then it updates to the latest date set for this field.

**Comment by patricklafrance** [comment]
Yes this is expected, `onDateChange` is called everytime a valid date is entered. The min/max threshold are then applied on blur and `onDateChange` will be called again if a clamp was required to meet the min/max threshold.

From what I understood in my last conversation with Alex, Apricot send an update to the API on blur so it should work. Are you sending the update on blur or `onDateChange` ?

**Comment by LaurentDario** [comment]
In that case, the update is sent on `onDateChange`. I guess best would be to change it for onBlur then

**Comment by patricklafrance** [comment]
Yes you should change it to `onBlur`.

I believe there is some work to be done to ensure a consistancy in Apricot behaviors.

My take is that every fields which are saved "automatically" should be saved "on blur" and the other fields should be saved manually by pressing some kind of save button.

This is the 2 behaviors I keep in mind when I develop a component in Orbit.

**Comment by LaurentDario** [comment]
I agree on those behaviors. For this specific case, do we have access to the `onBlur` of the `DateInput`?

**Comment by patricklafrance** [comment]
Of course you do!

**Comment by LaurentDario** [comment]
I tried to implement the onBlur and realized that the date was still sent wrong. So I tried a test on the documentation and managed to replicate.
If you enter a date prior to `min`, it will send the wrong date on Blur twice before it sends the right one.

Recording: https://share.getcloudapp.com/YEuZOeB5
And if it doesn't work cause it doesn't seem to play for me... here's a screenshot: 
![image](https://user-images.githubusercontent.com/234418/122940526-8b1a7000-d342-11eb-8afb-e1ff0eef7d0f.png)

**Comment by patricklafrance** [comment]
👍🏻 indeed, it seems broken. Sorry my tests on this were pretty weak, i'll have a look after lunch!

**Comment by patricklafrance** [comment]
Sorry, I have been stuck on another bug. The problem is that you are using `e.target.value` instead of `onDateChange` to get the value.

You should do something like this:

```
const dateRef = useRef();

return (
     <DateInput
           onDateChange={(event, newDate) => {
                dateRef.current = newDate;
           }}
           onBlur={() => {
                save(dateRef.current);
           }}
     />
);
```

You can use `useState` instead of `useRef` if you don't mind about extra rendering.

**Comment by patricklafrance** [comment]
This is not really developpers friendly... I do have a few things to prioritize but I have an idea which might improve the usage. I'll get back to you when it's done, should be before the end of the week.

**Comment by LaurentDario** [comment]
Par of the problem was also using `value` to initialize the value of the field with the previously saved date instead of using `defaultValue`. That's also something to keep in mind if anyone gets into that problem in the future!
`useRef` solved the rest of it. Thank you!
