### ISSUE TITLE
🐛 Documentation of retina image isn't accurate

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#697]
## Describe the bug
https://orbit.sharegate.design/?path=/docs/image--shape#retina
required props src is not present, and the example refers a props that does not exist in the documentation below

![image](https://user-images.githubusercontent.com/38871812/123825118-a1897400-d8cc-11eb-9106-9781c95563bd.png)

**Comment by patricklafrance** [comment]
`srcSet` is a native props and all components doesn't document native props except a few exceptions. We expect to list all supported props someday but we ain't there yet.

That being said, indeed we might want to add `srcSet` to allow `src` to be optionnal when a `srcSet` is provided.
