### ISSUE TITLE
❗ Create a variation of the date picker with buttons outside the field

### ISSUE THREAD

**Issue by Matthieu-Ortalda** [gsoft-inc/sg-orbit#703]
The buttons outside the date field would act as a way to select the timeframe for the view.

Behaviour:
- Changing the value of the timeframe using one of the buttons resets the content of the input
- Changing the content of the input does not select the corresponding button

**Comment by patricklafrance** [comment]
Thanks for the issue. Do you have a screenshot of the resulting look and a link to a figma file?

**Comment by Matthieu-Ortalda** [comment]
The component is not yet integrated to Figma but [here it is in the context of an experience](https://www.figma.com/file/KpAjPb07GUAP3R0Z2YRrBC/Trigger-Rewards-Automated-Teams-Governance?node-id=8073%3A1401)
