### ISSUE TITLE
❗ Add a "clearable" prop on the DateRangeInput component

### ISSUE THREAD

**Issue by laurentfrenette** [gsoft-inc/sg-orbit#704]
## Description

Following a discussion with a designer, we would like to be able to remove the "x" on the DateRangeInput component, as we don't want to allow the user to clear the inputs since we provide default dates.

A nice and easy way could be to have "clearable" boolean props.

![image](https://user-images.githubusercontent.com/45023868/125486024-7976f054-f5eb-4439-b898-08ff022209e0.png)

**Comment by patricklafrance** [comment]
Hi @laurentfrenette 

A [readonly prop is available](https://orbit.sharegate.design/?path=/docs/date-range-input--default-story#readonly) if you need to prevent the user from modifying your default dates.

**Comment by laurentfrenette** [comment]
> Hi @laurentfrenette
> 
> A [readonly prop is available](https://orbit.sharegate.design/?path=/docs/date-range-input--default-story#readonly) if you need to prevent the user from modifying your default dates.

For our use case, the readonly prop is of no use as we want to prevent the user from clearing the inputs while allowing him to edit the dates.

**Comment by patricklafrance** [comment]
I see, I am not convince it is a legitimate use case. We aim for consistency across the app which also mean offering components with the same behaviors in most of our experiences. I don't mind adding a few additional props for specific use cases but I don't see how making the input not clearable  in this case will benefit the user experience and is worth it.
