### ISSUE TITLE
🌟 Collect customer feedback to validate dark mode value to existing users

### ISSUE THREAD

**Issue by Matthieu-Ortalda** [gsoft-inc/sg-orbit#706]
## Description

We want to reach out to existing Apricot customers with a survey to validate that a dark mode brings them value in terms of accessibility, perceived ease of use and memorableness.

## Checklist

- [ ] Video presentation with a dark mode theme of a widely used flow
- [ ] Question for customer survey

**Comment by fraincs** [comment]
Since Orbit is now fully dark mode compatible and our apps are now getting ready to be dark mode compatible I am closing this issue.
