### ISSUE TITLE
💡 Use font-display Swap

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#710]
According to [web.dev](https://web.dev/font-display/), using `font-display: swap` on `TT Interphases` will improve the user experience by ensuring we're not showing invisible text on load.

## Problem to solve

Add `font-display: swap` to `@font-face` for TT Interphases.

**Comment by patricklafrance** [comment]
Interesting, did you tryed it directly in Apricot? If so, did you notice an improvement?

**Comment by fraincs** [comment]
font-display: swap has to be attached to the font declaration, who is declared in Orbit

**Comment by LaurentDario** [comment]
I quickly tested it out on my local by changing the content of @orbit-ui/fonts but to be honest, I'm not really seeing any invisible font. The loading state doesn't display any text and usually by the time the loading is done, even throttling on a slow 3G connection, the font is loaded.

**Comment by patricklafrance** [comment]
What do you think @fraincs should we add it? Seems low cost to me.

**Comment by fraincs** [comment]
Yes @patricklafrance cost nothing except build time. Let's do it.
