### ISSUE TITLE
🐛 Message: Flicker on first state change

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#740]
## Describe the bug

We use Message in the Settings page, alongside inputs that are updating the dates displayed in the Messages.
The state update seems to be provoking a flicker on all the Messages under that state, that we are able to reproduce in the documentation.

## Steps to reproduce

Include the Message in a State change. The Message then flickers for the first change. This does not happen then for any further changes:
![orbit-message-flicker](https://user-images.githubusercontent.com/234418/131693664-7c5b195a-1091-40cf-8450-7bcbf2a579f9.gif)

## Expected results

No flicker on change.

**Comment by patricklafrance** [comment]
Added the issue to our development board to investigate what's going on.

**Comment by alexasselin008** [comment]
Repro code

https://orbit.sharegate.design/?path=/docs/message--default-story#controlled


```
() => {
    const [count, setCount] = useState(0);

    const toggleVisibility = useCallback(() => {
        
    }, [setCount]);

    return (
        <Stack minHeight="110px">
            <Button variant="secondary" onClick={() => setCount(x => x + 1)}>
Increment Count
            </Button>
            <Message show>
                <Content>{count}: We offer the safest space travel of the industry!</Content>
                <Button>Book now</Button>
            </Message>
        </Stack>
    );
};
```
