### ISSUE TITLE
🐛  When Zoomed out a Listbox will show a scrollbar

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#741]
When zooming out a Listbox will show a scrollbar, this is due to the fact that we are using height in pixel instead of one in rem.

## Steps to reproduce

/?path=/story/listbox--default-story then zoom out (ctrl -)

## Expected results

The list shows totally.

**Comment by patricklafrance** [comment]
We should fix it. Our whole components suit should support zoom in/zoom out.

Do you need something from me to fix it?

**Comment by patricklafrance** [comment]
Awesome, let's close this then 🥳
