### ISSUE TITLE
🐛  SVG Props table is rather long

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#747]
## Describe the bug

![image](https://user-images.githubusercontent.com/361632/138768569-72a3e82d-90c8-49fe-b8e1-0fc2579ad17f.png)

The props table is not useful as it show too many properties.

## Steps to reproduce

/?path=/docs/image--shape#svgimage-1

## Expected results

A shorter more useful table.

## Reproducible demo

/?path=/docs/image--shape

**Comment by patricklafrance** [comment]
Are you planning on fixing this? Otherwise, I suggess closing this issue.
