### ISSUE TITLE
🐛  numberInput Increment/Decrement button does not show an active state

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#761]
## Describe the bug

Clicking a numberInput Increment/Decrement arrow button does not gives the active state to the button as the parent input gains focus and "wins", this is problematic as we can't style via CSS the buttons when they are pressed.

Adding an active class via JS seems to be the only solution.

## Steps to reproduce

Try to increment / decrement a numberInput and notice that the pressed is not applied but if you use dev tools to simulate an active state it works.

## Expected results

The active state is visible

## Reproducible demo

/?path=/docs/number-input--default-story

**Comment by LaurentDario** [comment]
This one is real tricky...
We are forcing the focus into the field when we click on an arrow:
```
    const handleStepperFocus = useEventCallback(() => {
        inputRef.current.focus();
    });
```
Not sure how to make sure we get the time have the active style applied before moving the focus...
