### ISSUE TITLE
❓ Type safety in mdx files

### ISSUE THREAD

**Issue by apdrsn** [gsoft-inc/sg-orbit#763]
Hi and thank you very much for making your code public - it's a very nice and comprehensive styleguide. 👍 
I am in the middle of creating one for my company using more or less the same stack. React, typescript and storybook.
I am very curious to find out if you managed to get mdx to check for types? I love the idea of making custom stories, but I don't like that it breaks my build without letting me know. I also experienced that it breaks without notice, if the file is missing a line break between code and heading for instance. Have you also experienced that?

Again - thanks a lot for letting your code live where I can learn from it. 💯 
And I hope it is okay that I ask you about this :)

Kind regards,
Anders

**Comment by alexasselin008** [comment]
Hi Anders!

Glad our repo could help you. 

Sadly we did not find a way yet to statically check types in mdx files . I'm following [this issue](https://github.com/microsoft/TypeScript/issues/36440 ) on the TypeScript github, hoping that they support it one day. 

As for the line breaks between the code and the heading, i haven't experienced that, but maybe @patricklafrance has.

**Comment by patricklafrance** [comment]
Hi @apdrsn 

We also experienced issues with line breaks. [MDX 2.0](https://github.com/mdx-js/mdx/issues/1041) should fix these issues but I think there is still a long way to go until it's release.

**Comment by apdrsn** [comment]
Thank you very much for the reply, @patricklafrance and @alexasselin008.
We'll just need to be patient and hope that it will arrive at some point.
I'll stick with CSF format for now (even though that also have some issues).
Have a very nice weekend 👍
