### ISSUE TITLE
🐛 ButtonGroup renders differently depending of browser

### ISSUE THREAD

**Issue by BobbyWhiskey** [gsoft-inc/sg-orbit#768]
ButtonGroup have a different orientation of buttons in Firefox vs Chrome

In chrome
![image](https://user-images.githubusercontent.com/16709076/140967094-b72dd1f4-0770-480b-86b0-cef1c8c29750.png)

In firefox
![image](https://user-images.githubusercontent.com/16709076/140966912-3e51d235-6c58-4da5-a2ae-aa2a6ba2915a.png)

## Steps to reproduce
Can be reproduced using the example for group of buttons in different browsers : https://orbit.sharegate.design/?path=/docs/modal--default-story#buttons

## Expected results
I assume Chrome renders correctly the buttons so it should be identical in Firefox

**Comment by alexasselin008** [comment]
Multiple errors are present in firefox 
![image](https://user-images.githubusercontent.com/38871812/141899738-22775d28-00bc-44c6-8d2b-cd12135a7596.png)

A quick investigation seems to point to the 
```
    box-sizing: border-box;
```

that is put on every element type in html.css file. 

This property didn't seem to be present before version 21.

@fraincs Could this be the issue?

**Comment by fraincs** [comment]
> Multiple errors are present in firefox ![image](https://user-images.githubusercontent.com/38871812/141899738-22775d28-00bc-44c6-8d2b-cd12135a7596.png)
> 
> A quick investigation seems to point to the
> 
> ```
>     box-sizing: border-box;
> ```
> 
> that is put on every element type in html.css file.
> 
> This property didn't seem to be present before version 21.
> 
> @fraincs Could this be the issue?

Will look into it, box-sizing border-box was there before only applied to `*` and directly on the element. Will start my investigation.
