### ISSUE TITLE
🐛 The Autocomplete component "no results found" state is unstyled.

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#776]
## Describe the bug

The Autocomplete component "no results found" state is unstyled.

![image](https://user-images.githubusercontent.com/794579/142561153-fa30b864-315d-436d-b5c7-4a2e11a17d89.png)

## Steps to reproduce

Go to https://orbit.sharegate.design/?path=/docs/autocomplete--default-story

Type "a" in the "Default" story

**Comment by fraincs** [comment]
This has been fixed in a other branch.
