### ISSUE TITLE
🐛 Autocomplete "no results" box should have the same width has the textbox

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#780]
## Describe the bug

![image](https://user-images.githubusercontent.com/794579/142974046-c0c030b2-bf32-4a71-9257-da4e8a59b71b.png)

Autocomplete "no results" box should have the same width has the textbox

Now:
## Steps to reproduce

Before:
![image](https://user-images.githubusercontent.com/794579/142974069-04ac04e5-c093-420d-801b-fd21957e798d.png)

Source: https://612943aef6c8f30007a0f3e0--sg-orbit.netlify.app/?path=/docs/autocomplete--default-story

**Comment by fraincs** [comment]
![image](https://user-images.githubusercontent.com/361632/143077535-838fb904-1d06-44a8-b76d-4c14cb3e06f3.png)

What's the consensus if a custom message is too long?

**Comment by patricklafrance** [comment]
@fraincs it should have the same behavior has in the previous version:

![image](https://user-images.githubusercontent.com/794579/143133111-469ce7bf-63e6-413d-aa36-2682c4251d36.png)
