### ISSUE TITLE
🐛 Spinner should be visible when an async tab is loading

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#783]
## Describe the bug

Spinner should be visible when an async tab is loading

![image](https://user-images.githubusercontent.com/794579/142975373-3945d78f-64de-4add-aaa4-4ad9508e8e66.png)

## Steps to reproduce

Go to: https://deploy-preview-779--sg-storybook.netlify.app/?path=/docs/tabs--default-story

Switch between tabs

**Comment by fraincs** [comment]
fixed on 22.0.1
