### ISSUE TITLE
🐛 Tile example with an illustration seem to have an error.

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#785]
## Describe the bug

The following example seem to have 2 errors.

![image](https://user-images.githubusercontent.com/794579/142975766-e22fb139-0857-45ee-9bd1-8c380e12b206.png)

1- It seem like the "color" prop in provided when I think the intent is to set a background color

2- If a "color" prop if set, if should apply to the text color but it doesn't seem to have any effect. Is it a bug?

## Steps to reproduce

Go to: https://deploy-preview-779--sg-storybook.netlify.app/?path=/docs/tile--tile#image

Scroll to the illustration example

**Comment by alexasselin008** [comment]
@patricklafrance color is set on the illustration, not the tile. So the color is not affected because there is no text in its children. Setting color on the tile works fine. 

I changed the backgroundColor property however, good catch
