### ISSUE TITLE
🐛 Button text doesn't seem to perfectly vertically centered

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#787]
## Describe the bug

It might be "an illusion" but the text of a button doesn't seem to be perfectly vertically centered.

![image](https://user-images.githubusercontent.com/794579/142976065-495b2ad4-22b1-4a1d-9ac3-e0b17a1cee30.png)

When looking at the button with dev tool, you can see that the dashed rectangle is a pixel off at the bottom.

![image](https://user-images.githubusercontent.com/794579/142976112-f732aca6-5f7b-4d26-a37b-465b19e11716.png)

## Steps to reproduce

https://deploy-preview-779--sg-storybook.netlify.app/?path=/docs/transition--page#example

**Comment by fraincs** [comment]
This is probably the old problem that will be fixed eventually via a new CSS prop: 

https://spectrum.chat/figma/general/text-not-vertically-centered-within-bounding-box~cbbb8752-df7e-48eb-ae59-ed2de739bbec for an example. 

Or a more detailed explanation here

https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align

this fix is too complicated given that a single CSS line fix is "on the way".

**Comment by fraincs** [comment]
> I am not sure this case match the example you linked.

Indeed the first example was for Figma I will edit my comment

**Comment by fraincs** [comment]
Upon closer inspection all is good, that said secondary button looks wrong size wise because it's using a box shadow and not a border, there use to be a reason for this, I think we could move to a border instead of a box shadow without any problem.
