### ISSUE TITLE
🐛 Docs theme switcher only have a single choice

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#792]
## Describe the bug

Since the theme switcher in Orbit docs only have a single choice, you should consider removing it if you don't intend to support multiple theme for the docs.

![image](https://user-images.githubusercontent.com/794579/143133618-7669941d-e9f0-4756-b83e-12d5ddf77ec7.png)

**Comment by fraincs** [comment]
It makes sense to remove it since it serves no purposes.
