### ISSUE TITLE
❗ SUGGESTION - You should remove native CSS named colors from TypeScript typing

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#793]
## Description

You should remove the native CSS named colors from TypeScript typing since it shouldn't be used and remove the focus from the actual legit colors values.

![image](https://user-images.githubusercontent.com/794579/143136096-063becfa-3700-4434-8671-618c54bd26a1.png)

**Comment by fraincs** [comment]
https://github.com/gsoft-inc/sg-orbit/releases/tag/22.0.3

**Comment by alexasselin008** [comment]
@fraincs i haven't seen any code trying to fix this issue in your PR

**Comment by fraincs** [comment]
> @fraincs i haven't seen any code trying to fix this issue in your PR

indeed, will look into it
