### ISSUE TITLE
🐛 Nesting cards with different orientation cause rendering issues

### ISSUE THREAD

**Issue by BobbyWhiskey** [gsoft-inc/sg-orbit#794]
## Describe the bug
When you nest multiple cards with images with different orientations, the content is not placed correctly in the card
![image](https://user-images.githubusercontent.com/16709076/143488264-ec6b0f14-b413-41b7-9f68-6ec3af007871.png)
## Expected results

The content should not be placed on top of the image in the inner card

## Reproducible demo

```
<Card orientation="vertical" boxShadow={2}>
    <Illustration backgroundColor="alias-accent-light">
        <Image src={Planet} alt="Planet over another one" width="100px" />
    </Illustration>

    <Heading>Vertical parent card</Heading>
    <Content>
        <Card orientation="horizontal" margin="1">
            <Illustration backgroundColor="alias-accent-light">
                <Image src={Planet} alt="Planet over another one" width="100px" />
            </Illustration>
            <Heading>NASA</Heading>
            <Content>
                Horizontal card
            </Content>
        </Card>
        <Card orientation="vertical" margin="1">
            <Illustration backgroundColor="alias-accent-light">
                <Image src={Planet} alt="Planet over another one" width="100px" />
            </Illustration>
            <Heading>NASA</Heading>
            <Content>
                Vertical card
            </Content>
        </Card>
    </Content>
</Card>
```

**Comment by fraincs** [comment]
I don't think Cards are meant to be nested.

**Comment by BobbyWhiskey** [comment]
Okay, do you want me to close the issue?

**Comment by fraincs** [comment]
> Okay, do you want me to close the issue?

I will make sure that this is an edge case and not reproductible in certain situations that are more common.

**Comment by fraincs** [comment]
While not being a problem, it revealed that the CSS rules were too loose, I made sure this won't happen by using more specific selectors.

**Comment by fraincs** [comment]
Fixed on https://github.com/gsoft-inc/sg-orbit/releases/tag/22.0.3
