### ISSUE TITLE
🐛 Storybook: Style props using the spacing scale are linking to sizing scale

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#798]
## Describe the bug

When clicking on a scale link for a prop using the Spacing scale in the [Styling > Props Reference doc](https://orbit.sharegate.design/?path=/docs/props-reference--page), the user is redirected to the Sizing scale

## Expected results

The user should be redirected to the [Spacing scale doc](https://orbit.sharegate.design/?path=/docs/spacing--page).

**Comment by fraincs** [comment]
Fixed on https://github.com/gsoft-inc/sg-orbit/releases/tag/22.0.3
