### ISSUE TITLE
🐛 ButtonAsLink should be exported with the button slot

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#805]
## Describe the bug

A card with a button, that works
```
<Card>
    <Heading>NASA Headquarters</Heading>
    <Header>No unexpected visitors allowed.</Header>
    <Content>
        <Paragraph>
            NASA Headquarters, officially known as Mary W. Jackson NASA Headquarters or NASA HQ and
            formerly named Two Independence Square, is a low-rise office building in the
            two-building Independence Square complex at 300 E Street SW in Washington, D.C.
        </Paragraph>
    </Content>
    <Button variant="secondary">Plan a visit</ButtonAsLink >
</Card>
```

A card with a buttonLink, wich doesnt work
```
<Card>
    <Heading>NASA Headquarters</Heading>
    <Header>No unexpected visitors allowed.</Header>
    <Content>
        <Paragraph>
            NASA Headquarters, officially known as Mary W. Jackson NASA Headquarters or NASA HQ and
            formerly named Two Independence Square, is a low-rise office building in the
            two-building Independence Square complex at 300 E Street SW in Washington, D.C.
        </Paragraph>
    </Content>
    <ButtonAsLink variant="secondary">Plan a visit</ButtonAsLink >
</Card>
```

## Expected results

The second scenario should work without having to specify a slot

**Comment by kingbaub3** [comment]
Similar to this issue, the following code works with a Button but doesn't work with a ButtonAsLink.

Button:
![image](https://user-images.githubusercontent.com/6119223/144907550-3466b0b8-74d9-4eec-8b50-ace36f88b995.png)

ButtonAsLink:
![image](https://user-images.githubusercontent.com/6119223/144907637-05b11b01-ddd6-407a-8d96-a8c2a3ac4708.png)

**Comment by patricklafrance** [comment]
This issue makes me wonder if providing the ability to have a link which look like a button was a good idea?

From a user standpoint, if you see something which looks like a button, you'll expect an action. But in this case, once you click on the button you will navigate somewhere.

This is not a good user experience has UI should behave the way user expect them to behave.

Beware of this pattern and maybe try to raise this concern to your designer before implementing the design?

At least, something similar to the `<Link />` component `external` prop should be added to `<ButtonAsLink />` component so the link will be opened in a new tab and the `rel` prop would be set to "noopener noreferrer"

**Comment by alexasselin008** [comment]
I was thinking that too for the external props, it seems like a good idea. 

As for providing a button as link, i think we will always find uses for them. Examples that comes to mind are download buttons, or Open Sharegate Desktop button that navigate to our custom protocol sharegate://

**Comment by patricklafrance** [comment]
> As for providing a button as link, i think we will always find uses for them. Examples that comes to mind are download buttons, or Open Sharegate Desktop button that navigate to our custom protocol sharegate://

I agree there might still be some use cases. All i'm saying is too be vigilant about these usecases. Navigations use cases shouldn't be buttons.

**Comment by fraincs** [comment]
Fixed on https://github.com/gsoft-inc/sg-orbit/releases/tag/22.0.3 I suggest opening a new issue regarding if needed regarding what has been discussed in the comments.
