### ISSUE TITLE
🚀  Rethink the use of zIndex in Orbit

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#808]
## Description

Using zIndexes in our components is not a guarantee they'll always be in the "layer" we want, it is now recommended to use the isolation CSS property. As explained below: 

https://www.joshwcomeau.com/css/stacking-contexts

Removing zIndex in favour of staking contexts will make our components more predictable and remove Javascript code.

**Comment by patricklafrance** [comment]
Are you planning on doing this on the next 6 months?

**Comment by patricklafrance** [comment]
Closing then?

**Comment by fraincs** [comment]
Yup will close.
