### ISSUE TITLE
☂️  Add a usage section to all components doc page.

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#809]
## Description

When do we use an Alert versus a Card? When a secondary button should be used? These are questions developers and designers asks themselves a lot. Having clear usage descriptions within Orbit documentation would help making decisions, and following them.

https://www.duetds.com/components/alert/#usage is a great example.

**Comment by patricklafrance** [comment]
Also love Paste a lot https://paste.twilio.design/components/card
