### ISSUE TITLE
🐛  Password Icon and Lastpass autofill are competing for attention

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#812]
## Describe the bug

When a user uses LastPass, LastPass icon is shown above Orbit's Eye icon that allows to show what you've typed.

## Steps to reproduce

Use a password field and LastPass Chrome extension.

## Expected results

The two icons are not on top of each other.

**Comment by fraincs** [comment]
With the way we display our password icon, Password managers that adds their own icons over inputs gets in the way of the reveal password icon. See below

![image](https://user-images.githubusercontent.com/361632/147095212-a90c794e-7125-4027-bb44-51ecc888b99e.png)

While detecting the most common password managers this is not guaranteed to work when a third party updates it's code, nor works for obscure password managers.

This issues aims at finding an elegant solution to make sure these password managers icons never gets in the way.

**Comment by Chicoalvi** [comment]
Is it possible to detect if a user uses a password management software and this software displays its icon in the password field ?

If it is possible, we could adjust the positioning of our eye icon according to the presence or not.

**Comment by Chicoalvi** [comment]
or another solution more simple ![image](https://user-images.githubusercontent.com/16927274/147970474-04b8b3cb-8e58-4e35-afde-aa476e09b2b1.png)

**Comment by patricklafrance** [comment]
If we want to keep an inline "show" icon the common solution is to move all the input style on the wrapper.

For example:

```
<div class="wrapper">
     <input type="password" />
     <button type="button>View</button>
<div>
```

Move the input style (background, border, ...) on the wrapper element. Therefore, from a user standpoint, the button seem to be in the input. For a password manager, it can safely add it's CTA at the end of the input without overlapping our "view" button.

Ex here: https://vaadin.com/docs/latest/example?path=component/passwordfield/password-field-basic.ts

**Comment by fraincs** [comment]
Late answer but I think this is the sensitive solution, moving the input style to the wrapper element.
