### ISSUE TITLE
🐛 IconButton look weird and the size diverge between primary and secondary variants

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#814]
## Describe the bug

In the following gif, the proportion of the icon in the button seem off? The icon is very big.

Furthermore, the code sample switch the button from the "secondary" variant to the "primary" variant on hover and it seem to change the size of the button?

![tooltip](https://user-images.githubusercontent.com/794579/145084003-d7ae543e-4ebe-4949-b95d-f00f7eb0a2e3.gif)

## Steps to reproduce

https://orbit.sharegate.design/?path=/docs/tooltip--default-story#custom-trigger

**Comment by fraincs** [comment]
This is most likely due to secondary button using a border while a primary button doesn't this changes the available size in the button. This could be fixed by giving a border to a primary button the same color as the inside.

**Comment by patricklafrance** [comment]
Could be a good idea, if you have multiple button stack horizontal it would look silly otherwise!

**Comment by fraincs** [comment]
> Could be a good idea, if you have multiple button stack horizontal it would look silly otherwise!

they have the same dimensions though

**Comment by patricklafrance** [comment]
Why does the box size expand on hover then in my gif?

**Comment by fraincs** [comment]
This was an issue with the size of the button that is not supported by Orbit, I will modify the sample.
