### ISSUE TITLE
🐛 Type issue in PopoverTrigger

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#815]
## Describe the bug

Using a popovertrigger with the following code: 
```
        <PopoverTrigger dismissable={false}>
            {({ close }) => (
                <>
                    <Buitton>Trigger</Button>
                    <Popover>
                        <Heading>Manage your subscription</Heading>
                        <Content>
                    Access your subscription details, modify it if needed, and manage your license activations.
                        </Content>
                        <Button onClick={close} variant="primary">Got it</Button>
                    </Popover>
                </>
            )}
        </PopoverTrigger>
```

causes the following error : 
![image](https://user-images.githubusercontent.com/38871812/145106219-a01905c4-d1fa-4ed9-bae4-fa792d923196.png)

## Expected results

I would expect no typescript error

**Comment by patricklafrance** [comment]
Set a type in your code?

```
{({ close }: { close: () => void }) => (
```

**Comment by alexasselin008** [comment]
This works, i used it as a workaround. 

However, we know that the allowed child of a popover are either an array of 2 react element, or a render function that accepts an object with the close function inside. 

It should be reflected in the type so i can infer it on my side.

Sandbox example: 
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDejUYByEAJktgMoCeAdjABZIzBoCiAbknXAL5wBmUCCDgAiKARiiAsACg5wOkij90SOAAUIkTlAAqUYAHMjyjULABnXHLhw09YABsSEmgC586GMTJwAPnAAFEFgFpaeOGhOEJZInkHxcNR0jMxsnHQAlHAAvAB8cOwQwCQ8OQVwAFIUABoAdKxOSCBcMFlyPHJy-ACuNBjAEDRwwJYAYv2Dw0HsKE69SSg0VFmecwvqY3CTA8zDNrJ2EjC9UCMwVGBIEPxF84t5ublwAOR9e0M0r53dsh-TEZaHTKAzGUxQIJRRwuNw8TzAiC6MEmMzhNbVOqNZqtbg4WyjfhBMa7QFBBzOVxcLI5fFHOxwE5nEYU2FcKEEhn2GJxBIVQrzZQwIKiaKxJCiDr0uzlAl8JBOOKHLlM85wAA8+VZVJo6oA9Pk5b95P8pvsRnokJZhbSCaqRkFORrDdKGerEcjDKioC6uXYcFCxXFynlCnS-Qz7cEnRH1QAjXowGAHYYAYScLAA1rkojykHx8ums-qE0nhr6I3ApRGeF1XXZ9R7QV6IRWuTGNU39C3lG2-fHE8maPkAIJOGIlwfljuN7RI5vg3tO-UVqU8IA

**Comment by patricklafrance** [comment]
Not relevant anymore since render props are no longer supported.
