### ISSUE TITLE
🐛 Documentation field short input example is really short on mobile

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#820]
## Describe the bug

![2C188990-BFF9-4E30-AABC-833CF0947A4B](https://user-images.githubusercontent.com/794579/145590240-1f3429af-805e-4abd-a3e2-b68e0b1607c0.png)

## Steps to reproduce

https://orbit.sharegate.design/?path=/docs/field--input#custom-input

**Comment by fraincs** [comment]
Percentage based widths are frowned upon as this produce these kind of results, using a responsive prop could solve the issue.

**Comment by patricklafrance** [comment]
💯
