### ISSUE TITLE
🐛  Button as Link should not have type button

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#821]
## Describe the bug

When used as a link a button still adds type button to the element (<a>) this is invalid HTML and causes issues in Safari for iOS. In Safari you can't apply appearance none on a <a> element but type="button" applies a button style to the element. 

## Steps to reproduce

Use a buttonAsLink and inspect it

## Expected results

No type="button" is present when a button is an anchor element.

**Comment by alexasselin008** [comment]
This could be merged with a couple other buttonAsLink issues, to create a better implementation of that control

**Comment by fraincs** [comment]
while still invalid this issue with iOs was not because of a type button on a Anchor. Closing as it's trivial.
