### ISSUE TITLE
🐛 Button content should not wrap in messages

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#823]
## Describe the bug

![image](https://user-images.githubusercontent.com/38871812/145837991-1219fef1-09ec-494a-afd5-cf418bd5b40f.png)

Button Got it is wrapped on 2 lines

## Steps to reproduce
https://orbit.sharegate.design/?path=/docs/message--default-story#rich-content

```
<Message>
    <Content>
        <Heading>There are no more activations left!</Heading>
        Need to use ShareGate on a different workstation? Remove the activation below <span role="img" aria-label="" aria-hidden="false" class="o-ui-html-span">👇</span> then log into the migration tool with your ShareGate account. The license will be automatically activated on that workstation.
    </Content>
    <Button>Got it</Button>
</Message>
```

## Expected results

Got it should be on the same line

**Comment by patricklafrance** [comment]
I am not sure if it's the button text who shouldn't wrap. We can't know how long the button text could be. I agree for a short text it's weird but what about if the text "Click me for a supper dupper offer" ?

Something have to be done but I would also investigate other options.

**Comment by alexasselin008** [comment]
I would prefer to have to specify on my button that it should wrap when it's too long, rather than specifying on all buttons in message that i don't want them to wrap

**Comment by fraincs** [comment]
One option would be to always reserve a spot for a button, the content length is too long anyway (The ideal width of a paragraph is 40-55 characters) it's currently way more in this example. Also I am wondering what would happen if there's 2 messages and both with a different button, the ending of the lines would be non identical.

**Comment by patricklafrance** [comment]
> I would prefer to have to specify on my button that it should wrap when it's too long, rather than specifying on all buttons in message that i don't want them to wrap

Adding this kind of property on a Button is, in my opinion dangerous. Eventually, with this philosophy, you'll end up with a bunch of incoherent properties on the component to maintain.

I prefer a solution similar to what Francis propose. It needs to work for all the breakpoints though.

**Comment by fraincs** [comment]
![image](https://user-images.githubusercontent.com/361632/146070643-1e97b039-0fdc-4eb8-a3b5-fb2c1016dea6.png)
Here's an option I've seen in another Design System, realistically a button on two lines is not very great looking design wise, limiting the buttons dimensions and adding ellipsis if needed would be a graceful way to solve the problem.

**Comment by patricklafrance** [comment]
Maybe step one would be to define these rules with the designers and document them somewhere (maybe in Orbit docs?). Then, step 2, fix the issue?

Otherwise I fear in a year we'll end up with the same issue again because we forgot or the team changed.

**Comment by fraincs** [comment]
When a Message component has too much texts and a button has more than one word the button wraps, it shouldn't wrap, at least not that fast, more designs should be produced to represent extreme cases, e.g. button way too long, button way too long in a responsive context.

Do we add an ellipsis when a button is too long, what is the maximum length a button could be? If an ellipsis is a solution would that be for all buttons or just when inside a Message and other components?

This issues could be the starting point of a reflexion of the behaviour of buttons in components.

**Comment by Chicoalvi** [comment]
Following a discussion with the other designers :

No matter how big the label in the button is, it always remains preserved and it is the content on its left that decreases in width.

When we reach a really small size then, we can do as carbon. The action button goes below.

<img width="661" alt="Capture d’écran, le 2022-01-03 à 14 54 06" src="https://user-images.githubusercontent.com/16927274/147976720-4d243682-0f7b-477d-9f08-b4d63d25a0bd.png">

<img width="289" alt="Capture d’écran, le 2022-01-03 à 14 56 52" src="https://user-images.githubusercontent.com/16927274/147976855-0704953f-23c4-4391-bdf8-a0d7475e5fc8.png">

**Comment by fraincs** [comment]
Buttons would be only wrap in a Message if they are bigger than 320px, which should not happen, this will be coded once Figma is updated.
