### ISSUE TITLE
🐛 Styling is weird when hovering a Tile with an illustration

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#828]
## Describe the bug

Styling is weird when hovering a Tile with an illustration

![tile](https://user-images.githubusercontent.com/794579/146490785-7a1bdd41-f169-4ee3-b860-b2a0a900df3a.gif)

## Steps to reproduce

In Storybook at ?path=/docs/tile--tile#image

**Comment by fraincs** [comment]
This seems to be aggravated by the fact that the default border is very pale (low break) almost imperceptible. Using mid break by default and hard break on hover could be a solution.

**Comment by fraincs** [comment]
A default tile has a light border, `low-break`, on hover it receives a `mid-break` color, this results in a weird visual effect, as if the border was non present on the default tile. A new design for the default/hover state could be done in order to mitigate the weird hover state when an illustration is present (see : https://orbit.sharegate.design/?path=/docs/tile--tile#image).

Another option is to modify the behaviour when an image is present.

Some research could be done in other design system to find a clever way to address the issue. Will update the issue if something emerges.

**Comment by Chicoalvi** [comment]
Clearly with others designers, we saw some little bugs (cf image). It should be discussed with the front-end.

<img width="118" alt="Capture d’écran, le 2022-01-03 à 14 30 44" src="https://user-images.githubusercontent.com/16927274/147972013-ac67a33c-b412-48b4-aaba-fb3519fbf725.png">

However, it is obvious that this component with a "touching the edges" image is complex. And considering a particular behavior is not consistent and increases the complexity of your system. This is just my point of view but I would consider using images with transparent backgrounds that do not touch the edges of the tile. See the zendesk example

<img width="862" alt="Capture d’écran, le 2022-01-03 à 14 43 10" src="https://user-images.githubusercontent.com/16927274/147973078-e70744fc-6a5b-48ea-8ca5-38a38c138244.png">

**Comment by fraincs** [comment]
It has been discussed that the hover state could only be the background color change. The default border color of a Tile would be bumped to mid-break instead of low-break.

A fix would still be needed for the problematic border-radius mismatch.

**Comment by charenk** [comment]
https://www.figma.com/file/20fCf5sGU27MEvyD2QSF5R/Inventory---Components-Usage?node-id=424%3A166499

**Comment by charenk** [comment]
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F20fCf5sGU27MEvyD2QSF5R%2FInventory---Components-Usage%3Fnode-id%3D429%253A167733" allowfullscreen></iframe>

**Comment by fraincs** [comment]
> Clearly with others designers, we saw some little bugs (cf image). It should be discussed with the front-end.
> 
> <img alt="Capture d’écran, le 2022-01-03 à 14 30 44" width="118" src="https://user-images.githubusercontent.com/16927274/147972013-ac67a33c-b412-48b4-aaba-fb3519fbf725.png">
> 
> However, it is obvious that this component with a "touching the edges" image is complex. And considering a particular behavior is not consistent and increases the complexity of your system. This is just my point of view but I would consider using images with transparent backgrounds that do not touch the edges of the tile. See the zendesk example
> 
> <img alt="Capture d’écran, le 2022-01-03 à 14 43 10" width="862" src="https://user-images.githubusercontent.com/16927274/147973078-e70744fc-6a5b-48ea-8ca5-38a38c138244.png">

The small bug with the border radius has been seen and is going to be fixed since we are removing the box shadow

**Comment by fraincs** [comment]
Seeing the new design I fear there will be no difference between a Card and a Tile apart from the hover state. A user won't be able to quickly tell a Card/Tile is interactive, this might be ok as the shadow was not that much of a hint that a Tile was a Tile. Just wanted to throw this out there before proceeding with the new design.

**Comment by patricklafrance** [comment]
I think you worked on this @fraincs ? Is it fixed?

**Comment by fraincs** [comment]
Yep closing the issue.
