### ISSUE TITLE
🐛  Tabs hover state is not obvious enough.

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#836]
## Describe the bug

Tabs hover state is not obvious enough.

## Steps to reproduce

Hover a tab, the change is subtle.

## Expected results

A user can easily distinguish he hovered a tab.

Here some inspiration:
- https://ant.design/components/tabs/ 
- https://atlassian.design/components/tabs/examples
- https://www.carbondesignsystem.com/components/tabs/code/

## Reproducible demo

https://orbit.sharegate.design/?path=/docs/tabs--default-story

**Comment by Chicoalvi** [comment]
We noticed inconsistencies in the behavior of custom tabs in Apricot (e.g. main navigation, dashboard navigation, tabs of group details), to discuss with the developers.

Following a discussion with other designers, a possible solution would be to add a small grey line (semantic/light/stroke/mid break) in addition to the label color change on hover.

something that would look like this 
<img width="694" alt="Capture d’écran, le 2022-01-03 à 15 47 32" src="https://user-images.githubusercontent.com/16927274/147979068-9d41cbe1-2c15-4b21-ae4a-fbee84e0acf9.png">
