### ISSUE TITLE
❓ Should BorderRadius accept "pill"

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#839]
Documentation seems to suggest that `borderRadius` should only allow 1-2-3-4 values, but the code accepts `pill`: https://github.com/gsoft-inc/sg-orbit/blob/master/packages/components/src/styling/src/styled-system/useStyledSystem.ts#L286

Should this option be removed?

**Comment by fraincs** [comment]
This has been done in another issue.
