### ISSUE TITLE
❓ Should Flex allow for flex: auto

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#841]
Currently we can use `flex: auto` on non Flex components, but Flex does not allow it.
Should it be allowed? Should it be just an `auto` prop?
Or should a Flex element never use `flex: auto`?

**Comment by patricklafrance** [comment]
I never used `flex: auto` a single time in my whole career haha. What are the use cases?

**Comment by LaurentDario** [comment]
While going through the examples I had I noticed that they were all fine with only `flex-grow: 1`.
`flex-auto` applies:
- flex-grow: 1
- flex-shrink: 1
- flex-basis: "auto"

I don't feel like it's a case we often need to cover but wondering if, as a design system, orbit should leave the door opened to a Flex element with flex auto:
> The item is sized according to its width and height properties, but grows to absorb any extra free space in the flex container, and shrinks to its minimum size to fit the container. This is equivalent to setting "flex: 1 1 auto".

**Comment by patricklafrance** [comment]
I don't have a strong opinion about this one. I tend to reduce the scope of what we support to only what we actually recommend or actually use.

It reduces the scope of what we have to maintain & document and I believe it's easier for the devs since they have less options.

**Comment by LaurentDario** [comment]
Sounds good, we'll see if it becomes necessary in the future but for now it looks like we can live without it!
