### ISSUE TITLE
💡 Documentation materials page should be merged in a single "Tokens" page.

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#842]
## Problem to solve

It's hard right now for a documentation reader to quickly find all the CSS Variables and Design Assets available in Orbit.

Furthermore, our current "Materials" pages offer a lot of information which are useless for a developer. Our original idea was that the documentation should be for both developers and designers but let's be honest in the end it's only for the developers.

## Idea

A "Tokens" page could offer a centralized and more concise documentation experience. Something similar to https://paste.twilio.design/tokens

A token entry could include: **Style Prop Value (when available)** | **CSS Variable** | **Value**  | **Exemple**

Maybe the word "token" is not appropriate since we don't have actual tokens in Orbit but I couldn't find a better name.

Once we have this page, maybe we could remove the "Reference" section of the style props page.

**Comment by fraincs** [comment]
> Once we have this page, maybe we could remove the "Reference" section of the style props page.

I am unsure about this one as the reference tables are providing more information like if a styleProps supports pseudo states, the CSS Property it affects, etc.
