### ISSUE TITLE
🐛 [Typography] Headings should have a font-weight of 700

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#843]
## Describe the bug

Talked about this issue with Francis already.

According to the Figma, Headings should have a font-weight of "Bold", which is 700. 
In orbit, the fontweight of the headings is 500. 

The 2 should be the same, so either fix it in figma or fix it in orbit

**Comment by fraincs** [comment]
Upon discussions with @GateNk 600 seems to be a good in between. 700 being a bit too bold.
