### ISSUE TITLE
🐛  Focus contrast in darkmode could be revised.

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#847]
## Describe the bug

When focusing on an element in dark mode the focus ring colour contrast could be enchanced.

![image](https://user-images.githubusercontent.com/361632/148576274-08c8b76c-fc5a-45ee-8be9-0a5fb971e0f3.png)

## Steps to reproduce

Focus on an input in dark mode.

## Expected results

The contrast is better.

**Comment by GateNk** [comment]
![image](https://user-images.githubusercontent.com/41477329/150203184-4ac0ebb3-4379-48ff-af9d-162fabba23e4.png)

Voici une nouvelle couleur pour le dark mode qui a un contrast ratio similaire pour le dark mode:
#3590DD  35%

**Comment by fraincs** [comment]
> 

magnifico
