### ISSUE TITLE
🐛 Focused item is hard to identify in a Menu component

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#848]
## Describe the bug

I was working on the Menu component and I though I had a bug because none of the menu item seemed to be focused when the menu opened.

Turns out I don't have a bug but the styling is not obvious. The following indicates that the "earth" item is focused:

![image](https://user-images.githubusercontent.com/794579/148576522-68a3d58d-4157-412a-af39-170d00d734c1.png)

I believe the focus indicator for the menu should have something matching our focus ring color:

![image](https://user-images.githubusercontent.com/794579/148576662-48a7e810-d442-41c0-b381-b1ef08cc2388.png)
![image](https://user-images.githubusercontent.com/794579/148576685-d7bea515-314f-47c0-9aa2-e36e497662a4.png)

My suggestion is to use something similar to spectrum:

![image](https://user-images.githubusercontent.com/794579/148576754-54b6b845-ae23-42a0-989b-0e12124d6512.png)

**Comment by GateNk** [comment]
I support the recommendation! This would bring it closer to how Listbox behaves

**Comment by fraincs** [comment]
@GateNk Can you document it in Figma?
