### ISSUE TITLE
🐛 Input components overflow their preview container in the documentation

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#858]
Our documentation should be responsive. Most input components (TextInput, Autocomplete, Select, etc.. etc..) min-width is large than the available space when using a mobile phone.

![image](https://user-images.githubusercontent.com/794579/148886248-65b48ee6-cace-4551-b561-2a077b9545c6.png)

We should come up with a strategy to mitigate this.

Either we automatically makes the input become fluid under a certains size and the preview container could be tweaked, for exemple to include a scrollbar.

**Comment by fraincs** [comment]
Maybe our inputs min-width are too long. Looking at Spectrum they are set at 192px. Given that most of the time our inputs will be fluid I think setting a shorter min width is an option.

**Comment by patricklafrance** [comment]
Yeah that would work.

My first though was to automatically make inputs fluid for smaller breakpoints but then I realize our min-width fits well in all our breakpoints. This is only a docs issue. So I don't know hehe. You proposition might be the one if it does work with the DA.
