### ISSUE TITLE
🐛 Accordion new font-weight looks too dark since the change to 600

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#860]
## Describe the bug

Orbit headings font-weight have been update from 500 to 600. Overall it seems OK but the Accordion components seem to dark to me?

Maybe it's the contrast with the icons?

![image](https://user-images.githubusercontent.com/794579/148887599-cb56a886-af45-4643-9abc-6b9ee08724af.png)

I would suggest overriding the Accordiong heading font-weight to 500.

**Comment by fraincs** [comment]
Totally. Going back to 500 is necessary.
