### ISSUE TITLE
❗ Update @sharegate/browserslist-config-recommended version

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#864]
## Description

We've updated the package for `@sharegate/browserslist-config-recommended` on npm, going from 1.0.1 to 2.0.0
The gist of it:
- We are a little more lenient towards the browsers we support going from `> 1%` usage to `> 0.2%`.

References:
- https://github.com/gsoft-inc/sg-browserslist
- https://www.npmjs.com/package/@sharegate/browserslist-config-recommended

**Comment by patricklafrance** [comment]
@LaurentDario have you been able to test that Orbit works well with the new browserlist config?

**Comment by LaurentDario** [comment]
@patricklafrance I tested storybook with the updated browserslist on my usual Chrome (latest) and an older version of Chrome and all the components run as they should. Do you see any other tests that we could run to make sure there's no impact?
I don't think that adding more supported browsers would impact Orbit that much.

**Comment by patricklafrance** [comment]
I was wonderwing how you tested it without making the update in Orbit.

Well, going from 0.2% to 1% include many more browser versions so I would make sure Orbit works with those versions.

Orbit code have been using the most edge CSS and JS features.

**Comment by LaurentDario** [comment]
The jump might be looking significant but when we look at the [usage table](https://caniuse.com/usage-table), it doesn't add that many browsers:
- Edge: no change
- **Firefox: adds 94**
- **Chrome: adds 92, 93, 94, 95**
- Safari: adds 13.1, 14, 15
- Opera: adds 81, 82
- Safari iOS: adds 13.7, 14.4, 15.2
- Android Browser: adds 4.4.4
- Firefox for Android: adds 95
- UC Browser for Android: adds 12.12
- Samsung Internet: adds 15.0

I highlighted the ones I think we should test. Happy to do more testing but so far on Chrome 92 and Chrome 96, it's looking good.

**Comment by patricklafrance** [comment]
Those should be tested before releasing an update to our browserlist package.

At least a validation with https://caniuse.com/ that the features used in Orbit are supported by the major browser versions we now support.

**Comment by patricklafrance** [comment]
To give you an example of something that I fear could break, Orbit use `:focus-visible`. I don't think `preset-env` can polyfill this. Is it supported by the new versions we support?

I think it does, it's only an example, but we should validate that those type of features are working before going forward.

**Comment by LaurentDario** [comment]
Checking on can-i-use, it looks like anything that is supported by the latest version of Chrome or Safari is also supported by those added versions: https://caniuse.com/?compare=firefox+94,firefox+95,chrome+92,chrome+93,chrome+94,chrome+95,chrome+96&compareCats=all
(currently covered: Firefox 95, Chrome 96)

**Comment by patricklafrance** [comment]
I won't go through the list, if you are confident everything is fine, it's fine with me.

For someone on the outside, reading that you only tested an older version of Chrome wasn't reassuring hehe :)
