### ISSUE TITLE
💡 Storybook doc: Only disable one of the buttons in Alert Disabled button example

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#867]
In storybook we're offering an example for Disabled Buttons, in Alerts. This example blocks the user in an Alert they can't dismiss because all buttons are disabled.

![alert-stuck](https://user-images.githubusercontent.com/234418/149545105-96d62daa-1338-4a46-b851-e196b220ed8d.gif)

## Idea

We could limit the disabled buttons to 1 of the 2 buttons. Or we could offer two examples with one disabled button in each example (to show that the user can disable any of the 2 buttons).

**Comment by patricklafrance** [comment]
Yeah!
