### ISSUE TITLE
❓ Alignement of a popover X button

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#868]
When I see it live, I am not sure about the position of the dismiss button of a popover?

![image](https://user-images.githubusercontent.com/794579/149603539-e5451c7f-c08f-4da0-b39f-f4a6ce5e4bc8.png)

Personally, I would align the end of the X with the end of the "Got it" button. And I would add more space over the dismiss button.

**Comment by fraincs** [comment]
@Chicoalvi thoughts?

**Comment by Chicoalvi** [comment]
Currently, the best alignment rendering (which I agree with) is with a margin-top = 8px and margin-right= 8px with a cross Button `<CrossButton aria-label="Clear"

<img width="1680" alt="Capture d’écran, le 2022-01-18 à 14 52 06" src="https://user-images.githubusercontent.com/16927274/150009121-6fc1d16a-752c-4acc-a377-c0cd0c06b3da.png">
`

**Comment by patricklafrance** [comment]
8px looks good to me!

**Comment by fraincs** [comment]
Do you have an example with a button? How would the title react if too long?

**Comment by Chicoalvi** [comment]
it looks like this 

<img width="611" alt="Capture d’écran, le 2022-01-18 à 16 18 19" src="https://user-images.githubusercontent.com/16927274/150020390-d18ab301-3792-475a-9066-c037812a7e65.png">

**Comment by Chicoalvi** [comment]
With a long title
I put a 2 rem margin-right on the title's div

<img width="497" alt="Capture d’écran, le 2022-01-18 à 16 35 30" src="https://user-images.githubusercontent.com/16927274/150022548-388ee959-f2f6-47cf-8d39-e3ef2ee4f4c7.png">

On the side of the design system of Salesforce, they have privileged a margin around the cross Button

<img width="1180" alt="Capture d’écran, le 2022-01-18 à 16 29 11" src="https://user-images.githubusercontent.com/16927274/150023283-d920d657-4c1c-4a80-be7d-96b094da80a5.png">

**Comment by fraincs** [comment]
LGTM
