### ISSUE TITLE
💡 Should we add a linter rule to help choosing between quotation marks and bracket

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#869]
This is more open for debate but should we add a rule to prevent people from using `""` where the value is coming from a numeric scale (like sizing or spacing) ?
 
## Problem to solve

Because we're introducing CSSinJS for the first time in our solution, we're starting to see some inconsistencies between the way devs are using the props in our codebase.

Currently, using `width={8}` is the same as using `width="8"`. Personally, I find it counter intuitive and I would expect that someone typing `width="8"` would try to make it `width: 8` in the outputted CSS (which, we agree, won't work).
This can get tricky with values that support simple numbers with no `px`, `%` or `em`, `rem`. For example, `lineHeight` or `fontWeight`.

## Idea

First of all I'm curious to see what everyone think about the use of quotes for those cases. It is still using the right variables (`width="8"` is outputting `width: var(--o-ui-sp-8)`). Should we **always** use `{}` unless we intentionally want to force a string value?

And if we think that we should use `{}`, what do you about adding a new rule that flags the use of `"number"` (except for identified exception, the only one I see we might want to leave open is `lineHeight`, maybe also `fontWeight`)?

**Comment by patricklafrance** [comment]
I agree with you this is a problem.

Even if it works, when using a scale value, Orbit expect the value to be numeric, therefore we should encourage the devs to use a number even if it does work with a string.

How would you do it with ESLint?

There might be a way to enforce it with TS but I am not sure how since the type do accept strings. Maybe @alexasselin008 have an idea.

**Comment by alexasselin008** [comment]
There is no way of doing this via typescript. We can suggest intellissense, but as long as we accept the "string" type, we will always be able to pass "4"

**Comment by LaurentDario** [comment]
How about something like that?
```
type Unit = "px" | "rem" | "em" | "%";
type NumWithUnit = `${number}${Unit}`;
export type WidthValue = keyof typeof SizingMapping | NumWithUnit | Exclude<Property.Width, string>;
```

**Comment by LaurentDario** [comment]
Je vois que le exclude exclude trop :/

**Comment by LaurentDario** [comment]
I see that the `Exclude` excludes a little too much...

**Comment by LaurentDario** [comment]
Ok I think I've got something working there:
```
type Unit = "px" | "rem" | "em" | "%";
type NumWithUnit = `${number}${Unit}`;
export type WidthValue = keyof typeof SizingMapping | NumWithUnit | Exclude<Property.Width, "TLength">;
```

Sorry for the spam!

**Comment by fraincs** [comment]
@tjosepo do you have an idea regarding this issue? A pair a fresh eye could be nice.

**Comment by tjosepo** [comment]
I've never encoutered this issue in the codebase I'm working in.

Personally, I don't mind `"8"` being converted into `{8}`.

**Comment by fraincs** [comment]
> I've never encoutered this issue in the codebase I'm working in.
> 
> Personally, I don't mind `"8"` being converted into `{8}`.

But "8" != { 8 }

**Comment by patricklafrance** [comment]
Since it doesn't seem to be doable, should this issue be closed?
