### ISSUE TITLE
💡 Integrate with code sandbox

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#870]
## Problem to solve

Bug reproduction are currently done by using Orbit documentation editable code samples. It works but it's not persistent and shareable.

## Idea

We could leverage codesandbox for this. Maybe with a codesandbox template or another feature. Here's a link to an official  Chakra codesandbox config: https://github.com/chakra-ui/chakra-ui/blob/main/.codesandbox/ci.json

**Comment by fraincs** [comment]
I had this in the back of my mind for a while.

**Comment by fraincs** [comment]
@alexasselin008 are we set to test it now?

**Comment by patricklafrance** [comment]
I doubt this is a priority. We should wait for the new dev to join the team.
