### ISSUE TITLE
🐛 Can't switch from one Popover to another on the same page

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#872]
When looking at storybook it appears that there is an issue when opening a Popover while another one is opened.

## Describe the bug

If you try to open a Popover while another is opened, there are 2 bugs happening:
- If the Popover that is already open is out of the view port, when opening the second Popover, it seems to move the page back to where the first Popover was.
- If the opened Popover is in view, the second Popover is directly closed when opened.

Screen recording: https://share.getcloudapp.com/Wnuql0qd

Error in console:
![image](https://user-images.githubusercontent.com/234418/149827238-6fb68f71-b311-4f62-a781-e03608b8210e.png)

## Expected results

While it is unlikely that we will be using Popover twice on the same page in our solutions, the expected behavior would be either:
- Allow 2 popovers opened at the same time (unlikely)
- Close the 1st popover before opening the 2nd one

**Comment by patricklafrance** [comment]
Other design systems only allow 1 popover at a time. Maybe after all this is what we should do. Doesn't really make sense to have 2 popovers opened.

It should be doable by configuring the popover to close on leave or outside click.

I wonder how that would work if a popover is "not dismissable" though... Since a "non dismissable" popover should not close on leave or outside click.

Maybe a "non dismissable" popover should have some kind of underlay like a modal?

Maybe "non dismissable" popover should not exist?

**Comment by fraincs** [comment]
In some situation two popovers open at the same time could make sense, on-boarding a new user or for a new feature, I’ve seen this in some apps.

**Comment by patricklafrance** [comment]
@fraincs got it!

I can't be sure until we find out what part of the code is causing the issue but my gut feeling tells me that supporting multiple popovers opened at the same time would be a lot harder.

If we have to do it, we'll try do it, but it would help if you could be more explicit about the use cases you think we might have at ShareGate for multiple popovers opened. That would help a lot of take the right decision.

Also, it would help to have the designers input on this.

**Comment by fraincs** [comment]
@Chicoalvi @GateNk @Matthieu-Ortalda

**Comment by LaurentDario** [comment]
Based on the design of the Popover I'm not sure how 2 Popovers could be opened at the same time.
They are trapping the focus inside of themselves, so you technically couldn't trigger a Popover while another one is opened (unless one Popover triggers the other one).

The current bug listed in the issue description seems to come from the Trap Focus. Not entirely sure yet why this is happening but I guess it is some kind of "race condition" or a problem with the focus trying to be put on the new Popover while the other closes and tries to bring back the focus on the trigger.

I'm trying to look into it more in depth.
