### ISSUE TITLE
🐛 Missing box-sizing on custom component as Button

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#876]
When using the `as` function to render a non-Orbit component as a Button (in that example, a React Router Link), the box-sizing is left to default `content-box`, making the button larger than it should be.

## Describe the bug

After removing Tachyons (which was forcing the rule `box-sizing: border-box` for `*, :after, :before`) we noticed that the size of buttons is not consistent.
![image](https://user-images.githubusercontent.com/234418/150028519-306b8a93-aab8-416f-8b43-1be45da92e34.png)

The button being fluid, the missing box-sizing forces it out of the container.

## Steps to reproduce

We use a `NavHashLink` as button:
```
const NavHashLinkAsButton = as(Button, NavHashLink);
```

Contrary to a Link as Button, it does not get added the `o-ui-html-a` class adding the right `box-sizing`.

## Expected results

Not sure if this falls onto Orbit or if it should be handled by the consumer.
If it should be handled by the consumer, a `boxSizing` prop could be added to the styled system.

**Comment by patricklafrance** [comment]
I think it should be handled by Orbit, what do you think @fraincs ?

Is is intentional?

**Comment by fraincs** [comment]
It is not intentional, the issue seems to be due to the fact that Orbit can't detect the NavHashLink is an `a` element. Should Orbit aware of third parties?

**Comment by patricklafrance** [comment]
@fraincs how would you do this?

**Comment by alexasselin008** [comment]
We have an Orbit Button that renders anything with the as property. Instead of trying to detect the anything and apply a box sizing to that, should we add the box sizing to all the orbit components directly?

if o-ui-html-button has box sizing set, why wouldnt o-ui-button have it?

**Comment by fraincs** [comment]
> @fraincs how would you do this?

I was not implying it was possible.

**Comment by fraincs** [comment]
> 

We were aiming to only set the box sizing on html elements and not other classes, in theory all Orbit components should use Orbit html elements, in this particular situation the rendered `<a>` is not an Orbit `a` element since it's provided by React Router.

**Comment by patricklafrance** [comment]
I think @fraincs nailed the problem and it's out of scope of Orbit.

**Comment by patricklafrance** [comment]
2- Wild idea...

1- I think we could refactor the "default style" classes to be `p.o-ui-html` instead of `o-ui-html-p`. Therefore, we could somehow add a "o-ui-html" class to an external component and it would benefit from orbit default styles. Maybe it could be added by the "as" function.

2- We could expose some kind of function to transform an external component into an Orbit component. Maybe for now it could only somehow apply Orbit default styles to the component.

**Comment by fraincs** [comment]
2 good ideas, adding `.o-ui-html` to every components could be a win.

**Comment by patricklafrance** [comment]
I’ll try something next week.
