### ISSUE TITLE
🐛 Wrap toolbar issue for small breakpoints

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#877]
## Describe the bug

The toolbar doesn't seem to properly wrap on multiple lines for small breakpoints.

I would expect the RadioGroup to wrap.

![wrap_toolbar](https://user-images.githubusercontent.com/794579/150361143-43cb3b80-7c70-4016-9c5b-013e9cba0ec0.jpg)

**Comment by fraincs** [comment]
The issue is that in order to show that a toolbar can wrap we need a parent with a fixed width (700px here) making this look broken on mobile. This will be fixed with a responsive style prop.
