### ISSUE TITLE
❗ Motions tokens should be available in the Tokens docs page

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#887]
## Description

We introduced recently a Tokens page. The idea is to offer a centralized page in which a dev can find out all the token and do a quick with "ctrl + f".

Therefore, I think the motions variables should be duplicated in the Tokens page.

**Comment by fraincs** [comment]
Even though they are not tokens per se? They are not generated by ShareGate theme.

**Comment by patricklafrance** [comment]
I don't define a token by something being defined by the theme.

These a variables that are intent to be used by apps, therefore for me, they are "tokens".

![image](https://user-images.githubusercontent.com/794579/151059001-f2d25a58-3763-4af9-99bd-6d84834d1baf.png)

**Comment by fraincs** [comment]
> These a variables that are intent to be used by apps, therefore for me, they are "tokens".

Gotcha, I am good with that.
