### ISSUE TITLE
🐛 When collapsing on multiple lines, the alignment of the action button seems wrong

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#888]
## Describe the bug

When collapsing on multiple lines, the alignment of the action button seems wrong because it's a tertiary button.

![image](https://user-images.githubusercontent.com/794579/151019403-1f6bb365-538d-43ad-931c-ff2dc192a32d.png)
![image](https://user-images.githubusercontent.com/794579/151019425-78a02807-3961-428f-9d46-0f60954655c6.png)

I am not sure what is the solution here. Maybe it's a no show.

**Comment by fraincs** [comment]
@GateNk should we proceed with the button rules discussed earlier? with those rules this button would be secondary right?

**Comment by GateNk** [comment]
@fraincs Correct! In Carbon, that gap is not as visible because the padding inside the padding is not as large as ours, but in our case it is a bit jarring, so I would indeed go with a secondary.

**Comment by GateNk** [comment]
@fraincs Sure!

- When an action is out of context and forces visual misalignment in Ghost, it should use an Outlined button. 
- If a Ghost button is close to a text and it is difficult to know which of the two is clickable, we use Outlined.
- If a button is displayed contextually (e.g. hover appearance) or is in a well-defined section (e.g. row of a table), you can use a Ghost

Use cases shown here: https://www.figma.com/file/Z7twTiHG6f6Thi4zZblYtp/Ghost-vs-Outlined!?node-id=0%3A1

**Comment by patricklafrance** [comment]
> @fraincs Sure!
> 
> * When an action is out of context and forces visual misalignment in Ghost, it should use an Outlined button.
> * If a Ghost button is close to a text and it is difficult to know which of the two is clickable, we use Outlined.
> * If a button is displayed contextually (e.g. hover appearance) or is in a well-defined section (e.g. row of a table), you can use a Ghost
> 
> Use cases shown here: https://www.figma.com/file/Z7twTiHG6f6Thi4zZblYtp/Ghost-vs-Outlined!?node-id=0%3A1

This is good stuff to add as usage guidelines in the button docs :)

**Comment by fraincs** [comment]
> This is good stuff to add as usage guidelines in the button docs :)

This would go in this initiative:  
https://github.com/gsoft-inc/sg-orbit/issues/809
