### ISSUE TITLE
🐛 Horizontal Illustrations should provide better positionning for heading and content

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#891]
## Describe the bug

![image](https://user-images.githubusercontent.com/38871812/151234377-bebc80ff-e8e0-43bb-a312-8f0790b1be0f.png)

The more i think about it, the more i think we should maybe split this component in 2. Illustration and illustratedImage.
because the position props makes it really weird. 

## Steps to reproduce
https://orbit.sharegate.design/?path=/docs/illustration--horizontal
```
<Illustration orientation="vertical">
    <SvgImage src={NoResults} stroke="alias-primary" />
    <Heading>Can't find "Saturn"</Heading>
    <Content>Please try another search</Content>
</Illustration>
```

## Expected results

In this case, the expected result would be something like this: 
![image](https://user-images.githubusercontent.com/38871812/151234579-9f4dd0e1-8daf-43d0-9769-5fdb95f9a764.png)

**Comment by GateNk** [comment]
Si ça peut aider, voici les règles qu'AlexV m'a partagé concernant les tailles d'images et le positionnement des textes:

> - Pour des images verticales, limitation à 320px de hauteur
> - Pour des images horizontales, limitation à 400px
> - Pour les images carrés ou presque, limitation à 320px
> - Espacement entre l’illustration et son bloc de texte à 40px.

Je n'étais pas au courant qu'on avait une composante ''Illustration'' qui gérait à la fois l'illu et le texte! :O 

On a des exemples ici de ce que ça donnerait pour nos empty states dans Teams management: https://www.figma.com/file/vcOOa3wctqiv1CJ57Akt5T/Empty-states?node-id=25%3A22905

**Comment by fraincs** [comment]
> i think we should maybe split this component in 2. Illustration and illustratedImage.

Totally, an Illustration should not deal with text. An IllustratedMessage using Illustration would make sense.

**Comment by alexasselin008** [comment]
It would fix the issue where a "vertical" illustration has the image and the text on an "horizontal" line, wich is really confusing

**Comment by patricklafrance** [comment]
We could seggregate the 2 components but I don't think we really have problem here. It's only a CSS bug. The text should spaced from the image.

**Comment by fraincs** [comment]
> The second does make sense and it could easily be fix.

The problem I am seeing is that when horizontal an illustration needs a dimension. 
![image](https://user-images.githubusercontent.com/361632/151570268-52f46eb4-94fa-4fba-9cda-b19edccc39cb.png)

Determining the illustration width with the added text could be tricky, thinking out loud I guess the width could be passed down to the image, or set to the Image directly.

**Comment by patricklafrance** [comment]
@alexasselin008 had a discussion about this issue on Slack. We could make it work easily for every use cases but it will indeed be easier for everyone if we splitted Illustration into 2 components.

Illustration will not do much, it will basically be the equivalent of

```jsx
<Flex alignItems="center" direction="row|column">
    <Image />
</Flex>
```

But still it's a design element and slots are preconfigured for an illustration in Card & Modal. So it still have a some value.

I won't name the other component "IllustratedImage" though, I would go for "IllustratedMessage".

So we would have:

- Illustration
- IllustratedMessage

**Comment by GateNk** [comment]
Regarding the conversation we had monday... Throwing this out there (to see if it sticks): maybe all illustrations should fit nicely in a square o_ô https://www.figma.com/file/vcOOa3wctqiv1CJ57Akt5T/Empty-states?node-id=44%3A78808

Don't be afraid to dunk on this idea ahah, I wasn't even aware this was a component until this week!

**Comment by patricklafrance** [comment]
@GateNk I think it works out of the box. The dimensions of the image and the dimensions of the "box" are defined by the developper.

An illustration component doesn't do much other than centering the image in the box, and offer predefined customization for the borders of the box.

**Comment by LaurentDario** [comment]
I agree with @patricklafrance on that, I think we should discuss this at our next sync but I'm leaning towards a very simple logic for the component itself. Within our products we can then decide what's the sizing for each usage.

**Comment by LaurentDario** [comment]
After discussing it with designers, the decision is to leave it be the way it wants to be but only force a maxWidth (overridable) of 864px for horizontal IllustratedMessages.

**Comment by patricklafrance** [comment]
@LaurentDario @GateNk maybe adding a square exemple in the docs could be the best of both world?
