### ISSUE TITLE
🐛 Form fieldset is not responsive

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#894]
## Describe the bug

Fields should collapse on multiple line.

https://orbit.sharegate.design/?path=/docs/form--vertical-layout#fieldset

![Fieldset](https://user-images.githubusercontent.com/794579/151670737-d14fdd41-aeb9-4577-a4df-feb66a0f14bc.png)

**Comment by fraincs** [comment]
Ended up refactoring a little bit of the Form css in order to better react to mobile layouts.
