### ISSUE TITLE
🐛 A modal with an image is not responsive

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#895]
## Describe the bug

(https://orbit.sharegate.design/?path=/docs/modal--default-story#image)

Similar issue with an Illustration.

![Modal illustration](https://user-images.githubusercontent.com/794579/151670824-6d020f15-7c4c-439a-a3c3-3498b7035028.png)

**Comment by fraincs** [comment]
This raises a bigger concern as of currently responsive layout is "supported" orbit via wraps mostly. Deliberately changing CSS per media queries was avoided, up until now. I am not against supporting this case but I'd like to find a way to do it without setting media queries, until container queries are supported.

**Comment by patricklafrance** [comment]
I get what you mean but by looking at [caniuse](https://caniuse.com/css-container-queries) it will take forever and meanwhile the UI is broken on small screens.

The image should either move to the top and be hidden on small screen.

Something similar to container queries can be emulated in React code without much effort.

**Comment by fraincs** [comment]
I saw some way to support Container queries with clever CSS or Javascript. Moving the image to the top would mean cropping it one way or another, which might not be what we want as we mostly use illustrations that should not be cut.

https://thumbprint.design/components/modal/usage/ Thumbprint do it this way : 

![image](https://user-images.githubusercontent.com/361632/154278242-63ebe64f-a849-4e45-975e-f6fe26cbadb6.png)

Which is responsive by default and does not requires two set of images.

Alternatively we could conclude that images in modal could be cropped when the image is on top but not when it's an illustration.

![image](https://user-images.githubusercontent.com/361632/154279942-7f17b957-c707-4617-8bca-5db144ee55f5.png)

Here I would have no problem modifying the layout as the illustration is Square and could easily be centered like in the above screenshot.

![image](https://user-images.githubusercontent.com/361632/154285148-91d6ad57-f7b9-4c3e-ab46-c0e8c170749b.png)

This is an alpha example not meant for production but gives an idea of what I mean.

**Comment by fraincs** [comment]
This would be problematic in this situation 
![image](https://user-images.githubusercontent.com/361632/154290095-2992ae9e-b010-4e3d-bae4-e0a7937284e4.png)

**Comment by patricklafrance** [comment]
@fraincs yeah I also though about this, that's why I also suggested "hidding the image".

For Thumbprint, you mean they solve it by always setting the image at the top instead of the side? That's a solution if the designers are up to it but I doubt it since it's a major change to the DA.

What do you think about hidding the image on small screen?

**Comment by patricklafrance** [comment]
@fraincs sounds good. Keep in mind that using an alternate image for mobile will not play well with current component design. Naïvely I think it would have to be in user land
