### ISSUE TITLE
🐛 A tile with row size is not responsive

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#897]
## Describe the bug

The tiles should try to take the available space.

(https://orbit.sharegate.design/?path=/docs/tile--tile#row-size)

![Tile row size](https://user-images.githubusercontent.com/794579/151671190-ced36b8c-905f-4e07-afe2-a3a0e511e80a.png)

**Comment by fraincs** [comment]
Layout drives responsiveness the sample has no layout, all those responsive issues should be in an umbrella issue, components are responsive per se but a responsive layout is needed, to tell them how to behave.

**Comment by patricklafrance** [comment]
I don't agree.

A tile group have a layout, even more with a row-size option.

If the consensus is that a tile group doesn't have a layout then I think the TileGroup component have to be removed and maybe a hook should be introduced for the group selection behavior.

**Comment by patricklafrance** [comment]
You can create an umbrella issue if you feel it will help you :)
