### ISSUE TITLE
🐛 Tile orientation docs example is broken on mobile

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#898]
## Describe the bug

(https://orbit.sharegate.design/?path=/docs/tile--tile#orientation)

![Tile orientation](https://user-images.githubusercontent.com/794579/151671255-6eefb1f7-dc1c-461c-bcc4-a5f85618ae4f.jpg)

**Comment by fraincs** [comment]
Otherwise 
![image](https://user-images.githubusercontent.com/361632/154334122-015c9f00-1f18-41b3-a8ee-d89983fa29e9.png)

it seems too cramped.

**Comment by patricklafrance** [comment]
@fraincs it seems like a good idea. I wonder thought if likewise the modal image issue we might encountered images wich doesn't fit horizontally & vertically?

**Comment by fraincs** [comment]
> seems like a good idea.

what seems like a good idea modifying the orientation or do it like the screenshot above.

we will for sure have cases where images don't fit both ways, an issue could be open in order to leverage CSS `object-fit` property where applicable, I am thinking Modal / Tile / etc

**Comment by patricklafrance** [comment]
@fraincs until we find a solution for https://github.com/gsoft-inc/sg-orbit/issues/895 I don't think switching the orientation of the card is a solution.

Still, your suggestion made me think about something... What if an Image component `src` prop becomes a responsive prop? That could fix it for Modal and Card.

For a card, it would be the responsability of the developer to:

- Use the responsive `orientation` prop to set the orientation base on Orbit breakpoints
- Set the responsive `src` prop according to the `orientation` prop

Since it would be in user land, an update would have to be made to the documentation to explain how it should be handled in the codebase.

**Comment by fraincs** [comment]
> @fraincs yeah but It wouldn’t leverage our existing breakpoints like a reponsiveProp would? I’m I missing something?

This has been fixed in https://github.com/gsoft-inc/sg-orbit/issues/921 closing this issue
