### ISSUE TITLE
🐛 Orbit does not work on a fresh CRA 5 project

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#902]
## Describe the bug

When creating a new Create React App project, using react-script 5.0.0, when importing orbit for the first time, we receive errors about the Icons.

```
ERROR TypeError: Cannot read property 'tagName' of undefined
```

## Steps to reproduce

```
npx create-react-app my-app
```

Follow Orbit's installation procedure : https://orbit.sharegate.design/?path=/docs/installation--page

## Expected results

The new application is able to use orbit component without errors

**Comment by alexasselin008** [comment]
This bug also prevent us from making online sandboxes with orbit with application like https://stackblitz.com/

**Comment by alexasselin008** [comment]
Patrick had similar issue when trying to update storybook to webpack 5. 

He suggests we try to move away from svgr.

**Comment by alexasselin008** [comment]
This also prevents 1SG and SG Apricot from moving to CRA5

**Comment by patricklafrance** [comment]
Related to https://github.com/gsoft-inc/sg-orbit/issues/853

**Comment by alexasselin008** [comment]
One approach we could take is to generator the react components at build time. Here are two relevant example from react spectrum and officevibe's igloo 
https://github.dev/adobe/react-spectrum/blob/91ca94fe52840b7a32b961ec08208f5fbdf65697/packages/%40spectrum-icons/ui/scripts/generateIcons.js#L24
https://github.com/gsoft-inc/ov-igloo-icons/blob/8f2b5f56e72375665758905d1d3fb97ee71d71d8/scripts/generate-component.js

**Comment by patricklafrance** [comment]
@alexasselin008 if you take a look at the root of Igloo repo, it's not exactly at build time that the icons are generated. They seem to do it manually and then commit the icons in the repo.

Take a look at the following folder https://github.com/gsoft-inc/ov-igloo-icons/tree/8f2b5f56e72375665758905d1d3fb97ee71d71d8/icon

**Comment by patricklafrance** [comment]
@alexasselin008 if you take a look at the root of Igloo repo, it's not exactly at build time that the icons are generated. They seem to do it manually and then commit the components in the repo.

Take a look at the following folder https://github.com/gsoft-inc/ov-igloo-icons/tree/8f2b5f56e72375665758905d1d3fb97ee71d71d8/components

**Comment by alexasselin008** [comment]
in the [package.json](https://github.com/gsoft-inc/ov-igloo-icons/blob/8f2b5f56e72375665758905d1d3fb97ee71d71d8/package.json) 
```
    "build": "yarn clean && node build.js && yarn babel",
```

[build.js](https://github.com/gsoft-inc/ov-igloo-icons/blob/8f2b5f56e72375665758905d1d3fb97ee71d71d8/build.js)
```
build(ICONS_SOURCE_DIR)
  .then((icons) => {
    // generate new svg files with svgo optimization
    generateSvg(icons, ICONS_DIST_DIR);

    // generate react components
    generateComponent(icons);

    // generate icons list for docs
    generateList(icons);
  })
  .catch((error) => console.error(error))
  .then(() => console.log('\n🚀 Build completed!\n'));
```

[generate-components](https://github.com/gsoft-inc/ov-igloo-icons/blob/8f2b5f56e72375665758905d1d3fb97ee71d71d8/scripts/generate-component.js)
```
const generateComponent = (icons) => {
  checkFolderExist(COMPONENTS_DIR);

  console.log('\n📦 Components generation...');

  const iconByName = icons.reduce((acc, icon) => {
    return merge(acc, {
      [icon.name]: {
        name: icon.name,
        heights: { [icon.group]: icon.data.trim() },
      },
    });
  }, {});

  Object.entries(iconByName).map(([key, icon]) => {
    const name = `${camelCase(key, { pascalCase: true })}`;
    const code = iconComponentTemplate(name, icon.heights);

    fs.writeFileSync(`${COMPONENTS_DIR}/${name}.jsx`, code);
  });

  console.log('✨ Components has been saved!');
};
```

So the build command builds the icon components and the publish them afterwards

**Comment by patricklafrance** [comment]
@franckgaudin could you give us a hint about why you commit the icon components in the repo if you build them before publishing?

**Comment by franckgaudin** [comment]
The reason for committing the components was that we were displaying the icons in the storybook for the doc. and do visual tests with Chromatic.
