### ISSUE TITLE
🐛 A tile hover style is too similar to the "checked" state

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#905]
## Describe the bug

A tile hover style is too similar to the "checked" state. Therefore, "unchecking" a Tile doesn't seem to work until you mouse out of the Tile.

I think the hover style shouldn't include a checkmark.

![tile_hover](https://user-images.githubusercontent.com/794579/153231624-75a6c528-a3f7-4d6e-90b7-63bb7d90311f.gif)

**Comment by patricklafrance** [comment]
That’s an option, how come the hover state must have a checkmark?

**Comment by pierre-lambert** [comment]
I'm worried about the affordance of this one. Since it has no hint of being selectable before the mouse-over, are users understanding well that it is clickable?

**Comment by patricklafrance** [comment]
Hey @pierre-lambert , do you mean on mobile or even on desktop? With a mouse, I think the "hover" state and the "hand cursor" should hint a user.

**Comment by pierre-lambert** [comment]
Yes, but waiting for the user to mouse-over the item does not provide enough affordance

**Comment by fraincs** [comment]
@pierre-lambert any ideas on where to go on this one?

**Comment by fraincs** [comment]
What other controls are you thinking about?

**Comment by pierre-lambert** [comment]
The Cards actually

**Comment by fraincs** [comment]
> shouldn't the checkmark be at the top-right instead of the bottom-right

This would cause problems when a Tile has an image as seen here: 

![image](https://user-images.githubusercontent.com/361632/170737455-1efbcdf4-f99b-4d76-83a5-3f530885556a.png)
