### ISSUE TITLE
🐛 SAFARI: Select and Autocomplete's overlay don't have the correct size on Safari.

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#908]
## Describe the bug

When using Safari, the select and autocomplete component display the following error in the console:  
```TypeError: undefined is not an object (evaluating '$(e.borderBoxSize)[0].inlineSize')```

This code is used in the useTriggerWidth's code. 

This is due to the fact that the resize-observer-polyfill doesn't have a polyfill for the borderBoxSize and contentBoxSize's properties, as per issue https://github.com/que-etc/resize-observer-polyfill/issues/77.

## Steps to reproduce

On Safari, open a page with a select or autocomplete control. Notice the error in the console.
The width of the overlay is also different: 
![image](https://user-images.githubusercontent.com/38871812/154120428-b9ac526d-9749-4fe0-918c-1d30d3b59e48.png)
expected : 
![image](https://user-images.githubusercontent.com/38871812/154120457-bce3288b-632c-4192-80c9-c06f7dc162c5.png)

## Expected results

The overlay's width should be the same as the trigger.

**Comment by fraincs** [comment]
I agree that this is a bug, at least it's non breaking since the options are visible and actionnable.

**Comment by fraincs** [comment]
@alexasselin008 any opinions?

**Comment by alexasselin008** [comment]
Another suggestion would be investigating if we can move away from borderBoxSize.

**Comment by fraincs** [comment]
This has been fixed on Safari side, testes on Safari Version 15.6.1 (17613.3.9.1.16) and no error in the console, the width is good too.
