### ISSUE TITLE
🐛 A bordered accordion button have an undesirable gap under the gray zone when touched

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#910]
## Describe the bug

A bordered accordion button have an undesirable gap under the gray zone when touched.

![273793294_937263063651742_5297677744442439909_n](https://user-images.githubusercontent.com/794579/154812283-37ce8ec3-88c8-478e-a3ed-222bde389f73.png)

**Comment by fraincs** [comment]
I guess this is on iOS? Chrome?

**Comment by patricklafrance** [comment]
IOS

**Comment by fraincs** [comment]
Upon inspection this is more a bug with Safari rendering engine 

![image](https://user-images.githubusercontent.com/361632/155763673-b6215d73-9b1e-4744-a3aa-7f2be5709312.png)

Closing in favour of #912
