### ISSUE TITLE
🐛A fullscreen modal is not wide enough on mobile

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#911]
## Describe the bug

On mobile a fullscreen modal take less horizontal space than a regular modal:

Fullscreen modal:

![image](https://user-images.githubusercontent.com/794579/155442929-194c8806-4808-46bd-9c5d-e66fa919e27a.png)

Regular modal:

![image](https://user-images.githubusercontent.com/794579/155442976-a450cb70-0b0a-49f6-9a31-362effd647ae.png)

On mobile, I would expect a full screen modal to really take the whole space, something similar to this:

![image](https://user-images.githubusercontent.com/794579/155443826-63b2973f-180d-4b6a-8851-9c168bcef9f9.png)

**Comment by fraincs** [comment]
In that case I would change the full screen description too

> A modal can take almost all the available space.

as it's not always true to : 

> A modal can take as much space as possible.

**Comment by patricklafrance** [comment]
It depends what we choose to do on desktop.

**Comment by fraincs** [comment]
> It depends what we choose to do on desktop.

True, I guess it won't be an easy fix after all.

**Comment by fraincs** [comment]
https://github.com/gsoft-inc/sg-orbit/issues/913 has been opened to tackle bigger issues, I will fix the padding of fullscreen modal in mobile per the issue and discussion regarding whether or not a fullscreen modal should take the whole viewport can take place in the issue above.

**Comment by fraincs** [comment]
Since Fullscreen Modals are no more, I am closing this issue.

**Comment by patricklafrance** [comment]
@fraincs it might not be called "fullscreen" anymore but I think the behavior of taking all the available space when on mobile should still be considered.

What do you think?
