### ISSUE TITLE
💡 Avatar has a default look when no name is provided

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#918]
On our app, we are currently using a Placeholder image for the User Image when no display name is available. This leads to some questionnable updates throughout the app lifecycle to handle more and more scenarios.
I was wondering if it would be a good update to handle the case where `name` would be undefined or null in the `Avatar` component, rendering a placeholder image (maybe a silhouette image) or going even further, being able to provide a default SVG to render as prop.

## Problem to solve

Avatar could be called with a null or undefined `name`. Should this be handled by the library's consumer or is there an opportunity to support it right in the Avatar component?

## Idea

Render a silhouette image, or offering the option to provide a default SVG to render if `name` is undefined or null

**Comment by patricklafrance** [comment]
Pretty sure we already had this discussion a few months ago and we concluded that it doesn't make sense in our apps to have an avatar without a name?

**Comment by fraincs** [comment]
Do you have a concrete case where it happens?

**Comment by LaurentDario** [comment]
There's not really a case where it is a problem as we currently have a custom component using the Avatar component while defaulting to a Placeholder if the name is undefined or null.
The suggestion was to have it handled on the Orbit side, but I understand that if it has been discussed in the past and it doesn't make sense to cover it there, we can keep it on our side. 👌

**Comment by LaurentDario** [comment]
The placeholder fallback is only really used if the session is empty, for the account avatar, or during loading states. 
```
if(isNil(user.displayName) && isNil(title)}) {
    <UserPlaceholderImage />
} else {
   <Avatar retryCount={1} src={src} name={title || cleanupDisplayName(user.displayName)} size={size} />
}
```

**Comment by patricklafrance** [comment]
Got it, so an O365 user can exist without name?

**Comment by fraincs** [comment]
@LaurentDario

**Comment by patricklafrance** [comment]
This is issue has been idle for a while. Is it still relevant or it should be closed?

**Comment by fraincs** [comment]
Waiting on @LaurentDario answer?
