### ISSUE TITLE
🐛  DatePicker Input is not wide enough clashing with password managers 

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#953]
## Describe the bug

When a password manager adds it's icon it overlaps with the input inside the datePicker component. 

![image](https://user-images.githubusercontent.com/361632/163190342-211f2fd7-40bb-4e40-8f2b-b50d171a2a29.png)

## Steps to reproduce

Using a password manager like Dashlane, visit the dateInput component.

## Expected results

There is enough white space to acknowledge these kinds of situations.

**Comment by fraincs** [comment]
The width is the same as a default input, apart from setting the default input wider, I see no other options. except live with the fact that password managers will mess up inputs once in a while, which happens here and there on the internet.

**Comment by patricklafrance** [comment]
I might be wrong, but I thought you already nailed this one?

**Comment by fraincs** [comment]
This was "nailed" then an edge case occured.

**Comment by patricklafrance** [comment]
Ok, are you planning on working on this in the next 6 months? @fraincs

**Comment by fraincs** [comment]
Yes, I need to discuss with a designer as our input default size would need to change.

**Comment by fraincs** [comment]
The issue here is that acknowledging the issue would need to make the DateInput size wider, which would require to make all Select / TextInputs / PasswordInputs. After thinking about it I am open to another option which would be to as much possible tell password managers to ignore this field. I don't see a situation where we would want to autocomplete a date range input field.

**Comment by patricklafrance** [comment]
I would also be opened to such a solution but I think we already discussed this solution and it's wasn't possible because there wasn't any common specification to tell a password manager to ignore a field and Dashlane offered no escape hatches to do so.

According to this [reddit post](https://www.reddit.com/r/Dashlane/comments/wnbwtc/stop_autofill/), there's seem to be a way with Dashlane now by adding `data-form-type: "other"` to the input.

**Comment by fraincs** [comment]
This is what I saw too, and is why I'm leaning towards this option. We
would ignore the few obscure passwords managers who don't provide a way to
opt out.
