### ISSUE TITLE
🚀  Recover documentation highlights that have been lost in an accessibility purge

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#964]
## Description

When the doc has been reworked some information that was highlighted using blockquotes `> ...` has lost it's appearance. Therefore we need a way to put the focus on important pieces of information be it a colored block, an emoji 👉🏻 , a NOTE: or some other way.

Attached some inspiration: 

![image](https://user-images.githubusercontent.com/361632/166725678-a84485ad-50d5-43c6-b0ae-d51b38c70493.png)
![image](https://user-images.githubusercontent.com/361632/166725697-48a28c69-9f92-47f0-bc96-e1a72626d22a.png)
![image](https://user-images.githubusercontent.com/361632/166725717-6ebdb384-fcde-4cfc-9c65-c1c05c863346.png)

**Comment by pierre-lambert** [comment]
Isn't "Message" fulfilling this need? https://orbit.sharegate.design/?path=/docs/message--default-story

**Comment by fraincs** [comment]
@pierre-lambert in some instances I think a Message is not fulfilling it's duty let's take this : 

In Orbit, 1 rem unit = 16 pixels.

This isn't a message for the user but more of a Tip what do you think?

Wouldn't something like this make more sense?

💡  In Orbit, 1 rem unit = 16 pixels.

versus this

![image](https://user-images.githubusercontent.com/361632/166934924-16913b9c-a01f-4e2d-8226-334caf2c36e9.png)
