### ISSUE TITLE
🐛 AvatarGroup shows incoherant avartar text alignment

### ISSUE THREAD

**Issue by dmainville** [gsoft-inc/sg-orbit#990]
## Describe the bug

The AvatarGroup component aligns the name of the avatar differently in the "info bubble" depending on if the avatar src was specified (name will be aligned bottom) or if it was auto-generated (name will be centered).

See screenshot :
![image](https://user-images.githubusercontent.com/2125714/173427174-553a1976-7a15-4193-827a-49d7d82ef35f.png)

## Steps to reproduce

Create an AvatarGroup like the following, see that the on over bubble shows different alignments : 
```
<AvatarGroup>
    <Avatar name="Sally Ride" />
    <Avatar name="Alan Shepard" />
    <Avatar src={ChrisHadfield} name="Chris Hadfield" />
    <Avatar name="1234" />
    <Avatar src={ChrisHadfield} name="adfasdf" />
    <Avatar name="AAAAA CCCCCC" />
    <Avatar src={ChrisHadfield} name="asdfasdfasdfasdf" />
</AvatarGroup>
```

## Expected results

I would expect all the inner avatar names to be of the same text alignment in the "info bubble" regardless of if the image is specified in the src or if it is autogenerated.

**Comment by fraincs** [comment]
fixed on 27.1.1
