### ISSUE TITLE
🐛 Unnecessary use of :where() in Heading and Text

### ISSUE THREAD

**Issue by wasim-abuzaher-sg** [gsoft-inc/sg-orbit#999]
## Describe the bug

The :where() pseudo selector is not being used correctly in Heading.css and Text.css! The selector is meant to be used to select apply CSS styles to a list of selectors! However it's being used to select just one class, which makes it redundant at best, and causing issues on older browsers with no :where() support (i.e. Microsoft Teams version on Chrome) 

## Steps to reproduce

Run the app, go to Heading.css and remove :where() selectors, notice that the styling doesn't change on storybook

### With :where()

![Screen Shot 2022-06-30 at 9 34 12 AM](https://user-images.githubusercontent.com/107011881/176691369-0abfd62f-8f4e-43be-9c8a-dc7748cac75a.png)

### Without :where()

![Screen Shot 2022-06-30 at 9 35 05 AM](https://user-images.githubusercontent.com/107011881/176691528-b7b42aae-cb62-4277-bef9-78b840b079f1.png)

## Expected results

Renders correct styles on browsers that don't support :where()

**Comment by fraincs** [comment]
:where is used to provide 0 specificity to orbit defaults, since we only support modern browsers this wasn't an issue that we foresaw.

**Comment by wasim-abuzaher-sg** [comment]
We could add a fallback to support older browsers (i.e. Teams app):
```
@supports not selector(:where(a)) {
    .o-ui-heading {
        margin: 0;
        font-size: inherit;
        font-weight: 400;
        font-variation-settings: "wght" 600;
        overflow-wrap: break-word;
    }
    //...
}```

**Comment by fraincs** [comment]
Be aware that without the `where` you'll enter some specificity wars with Orbit, I guess it's alright until Teams updates it's renderer.

**Comment by wasim-abuzaher-sg** [comment]
Will close issue, applying workaround in the teams-app project until Microsoft Teams upgrade their browser
